/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.6.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`organization_pricing_create_organization_pricing`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganizationPricingCreateOrganizationPricingError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organization_pricing_delete_organization_pricing`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganizationPricingDeleteOrganizationPricingError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organization_pricing_list_organization_pricing`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganizationPricingListOrganizationPricingError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organization_pricing_replace_organization_pricing`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganizationPricingReplaceOrganizationPricingError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// Set the organization's rate for a model over a period.  Refused with a 409 when the period overlaps one already stored for that model, naming the period it collides with, rather than shadowing it. Refused with a 403 when the model is addressed through one of the deployment's own provider instances: the deployment holds that credential and settles its upstream bill, so its rate is the deployment price list's rather than a tenant's.  The key is normalized to its canonical ``instance:model`` form first, the same call ``POST /api/v1/pricing`` makes, and that is what makes one model one row rather than one per spelling. Stored verbatim, ``openai:gpt-4o`` and ``openai/gpt-4o`` are two keys: the overlap rule would not see them as colliding, and both would resolve, with the canonical one preferred, leaving the other dormant until the first is deleted. Normalizing on the way in is what stops that pair existing at all.
pub async fn organization_pricing_create_organization_pricing(
    configuration: &configuration::Configuration,
    organization_model_pricing_create: models::OrganizationModelPricingCreate,
) -> Result<
    models::OrganizationModelPricingPublic,
    Error<OrganizationPricingCreateOrganizationPricingError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_organization_model_pricing_create = organization_model_pricing_create;

    let uri_str = format!(
        "{}/api/v1/organizations/me/pricing",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };
    req_builder = req_builder.json(&p_body_organization_model_pricing_create);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationModelPricingPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationModelPricingPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganizationPricingCreateOrganizationPricingError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Remove an override, returning the model to the deployment price list.
pub async fn organization_pricing_delete_organization_pricing(
    configuration: &configuration::Configuration,
    pricing_id: &str,
) -> Result<(), Error<OrganizationPricingDeleteOrganizationPricingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_pricing_id = pricing_id;

    let uri_str = format!(
        "{}/api/v1/organizations/me/pricing/{pricing_id}",
        configuration.base_path,
        pricing_id = crate::apis::urlencode(p_path_pricing_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganizationPricingDeleteOrganizationPricingError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List the organization's rate overrides.  Readable by any member: these rates decide what the caller's own requests cost, so they are not withheld from the people billed at them. Writing needs an owner or admin.  Paged on the same bounds the rest of the tenancy surface uses, because the table grows a row per model per period. ``count`` is the total, so a client knows whether another page is owed.
pub async fn organization_pricing_list_organization_pricing(
    configuration: &configuration::Configuration,
    skip: Option<i32>,
    limit: Option<i32>,
) -> Result<
    models::OrganizationModelPricingsPublic,
    Error<OrganizationPricingListOrganizationPricingError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_skip = skip;
    let p_query_limit = limit;

    let uri_str = format!(
        "{}/api/v1/organizations/me/pricing",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_skip {
        req_builder = req_builder.query(&[("skip", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationModelPricingsPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationModelPricingsPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganizationPricingListOrganizationPricingError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Replace an override's rates and period.  Future requests in the period price at the new rate; usage already settled keeps the cost it was billed, because a settled cost is stored on the usage row rather than recomputed.  Refused with a 403 on the same deployment-supplied-model rule the create path carries, so a row stored before that rule existed cannot be edited into a rate nobody could create today.
pub async fn organization_pricing_replace_organization_pricing(
    configuration: &configuration::Configuration,
    pricing_id: &str,
    organization_model_pricing_update: models::OrganizationModelPricingUpdate,
) -> Result<
    models::OrganizationModelPricingPublic,
    Error<OrganizationPricingReplaceOrganizationPricingError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_pricing_id = pricing_id;
    let p_body_organization_model_pricing_update = organization_model_pricing_update;

    let uri_str = format!(
        "{}/api/v1/organizations/me/pricing/{pricing_id}",
        configuration.base_path,
        pricing_id = crate::apis::urlencode(p_path_pricing_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };
    req_builder = req_builder.json(&p_body_organization_model_pricing_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationModelPricingPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationModelPricingPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganizationPricingReplaceOrganizationPricingError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
