/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`clear_workspace_web_search_config_v1_workspaces_workspace_id_web_search_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClearWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchDeleteError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_workspace_web_search_config_v1_workspaces_workspace_id_web_search_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_workspace_web_search_config_v1_workspaces_workspace_id_web_search_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchPutError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// Drop a workspace's configuration, returning it to the deployment's behavior.  Idempotent: a workspace that has no configuration is already in the state this asks for, so it answers with the unconfigured shape rather than a 404.
pub async fn clear_workspace_web_search_config_v1_workspaces_workspace_id_web_search_delete(
    configuration: &configuration::Configuration,
    workspace_id: &str,
) -> Result<
    models::WorkspaceWebSearchConfigPublic,
    Error<ClearWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchDeleteError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/web-search",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceWebSearchConfigPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceWebSearchConfigPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<
            ClearWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchDeleteError,
        > = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Read a workspace's web-search configuration.  Takes the same role as setting it (an organization owner/admin, or an owner/admin of this workspace), because the row describes the workspace's posture rather than one member's allowance. A workspace with no row answers with the unconfigured shape (``configured: false``), which is the deployment's own behavior described in the same shape rather than a 404.
pub async fn get_workspace_web_search_config_v1_workspaces_workspace_id_web_search_get(
    configuration: &configuration::Configuration,
    workspace_id: &str,
) -> Result<
    models::WorkspaceWebSearchConfigPublic,
    Error<GetWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchGetError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/web-search",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceWebSearchConfigPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceWebSearchConfigPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Set a workspace's web-search configuration, replacing any existing one.  An organization owner/admin, or an owner/admin of this workspace, may write it. The configuration can only narrow what the deployment permits: turning web search off for the workspace, lowering the result ceiling, and adding to the domains a search may not reach. It never turns on a backend the deployment has not configured, and it carries no credential.
pub async fn set_workspace_web_search_config_v1_workspaces_workspace_id_web_search_put(
    configuration: &configuration::Configuration,
    workspace_id: &str,
    workspace_web_search_config_update: models::WorkspaceWebSearchConfigUpdate,
) -> Result<
    models::WorkspaceWebSearchConfigPublic,
    Error<SetWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchPutError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;
    let p_body_workspace_web_search_config_update = workspace_web_search_config_update;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/web-search",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };
    req_builder = req_builder.json(&p_body_workspace_web_search_config_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceWebSearchConfigPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceWebSearchConfigPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetWorkspaceWebSearchConfigV1WorkspacesWorkspaceIdWebSearchPutError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
