/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_workspace_budget_default_v1_workspaces_workspace_id_member_budget_policies_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_workspace_budget_default_v1_workspaces_workspace_id_member_budget_policies_default_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesDefaultIdDeleteError
{
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_workspace_budget_defaults_v1_workspaces_workspace_id_member_budget_policies_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListWorkspaceBudgetDefaultsV1WorkspacesWorkspaceIdMemberBudgetPoliciesGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_workspace_budget_default_v1_workspaces_workspace_id_member_budget_policies_default_id_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesDefaultIdPatchError
{
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// Create a budget default.  Materializes it into a per-member ``scoped_budgets`` row for every existing active member of the workspace; a member who joins afterwards is materialized when they join.
pub async fn create_workspace_budget_default_v1_workspaces_workspace_id_member_budget_policies_post(
    configuration: &configuration::Configuration,
    workspace_id: &str,
    workspace_member_budget_policy_create: models::WorkspaceMemberBudgetPolicyCreate,
) -> Result<
    models::WorkspaceMemberBudgetPolicyPublic,
    Error<CreateWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesPostError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;
    let p_body_workspace_member_budget_policy_create = workspace_member_budget_policy_create;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/member-budget-policies",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };
    req_builder = req_builder.json(&p_body_workspace_member_budget_policy_create);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceMemberBudgetPolicyPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceMemberBudgetPolicyPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<
            CreateWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesPostError,
        > = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete a budget default.  The per-member ``scoped_budgets`` rows it already materialized are kept; a member joining afterwards no longer gets one from it.
pub async fn delete_workspace_budget_default_v1_workspaces_workspace_id_member_budget_policies_default_id_delete(
    configuration: &configuration::Configuration,
    workspace_id: &str,
    default_id: &str,
) -> Result<
    models::Message,
    Error<
        DeleteWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesDefaultIdDeleteError,
    >,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;
    let p_path_default_id = default_id;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/member-budget-policies/{default_id}",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id),
        default_id = crate::apis::urlencode(p_path_default_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Message`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Message`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesDefaultIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List the budget defaults attached to a workspace. Any member may read it.
pub async fn list_workspace_budget_defaults_v1_workspaces_workspace_id_member_budget_policies_get(
    configuration: &configuration::Configuration,
    workspace_id: &str,
    skip: Option<i32>,
    limit: Option<i32>,
) -> Result<
    models::WorkspaceMemberBudgetPoliciesPublic,
    Error<ListWorkspaceBudgetDefaultsV1WorkspacesWorkspaceIdMemberBudgetPoliciesGetError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;
    let p_query_skip = skip;
    let p_query_limit = limit;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/member-budget-policies",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_skip {
        req_builder = req_builder.query(&[("skip", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceMemberBudgetPoliciesPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceMemberBudgetPoliciesPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<
            ListWorkspaceBudgetDefaultsV1WorkspacesWorkspaceIdMemberBudgetPoliciesGetError,
        > = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update a budget default's label or limit.  Not retroactive: members already materialized from this default keep their existing ceiling; only a member materialized afterwards sees the new one.
pub async fn update_workspace_budget_default_v1_workspaces_workspace_id_member_budget_policies_default_id_patch(
    configuration: &configuration::Configuration,
    workspace_id: &str,
    default_id: &str,
    workspace_member_budget_policy_update: models::WorkspaceMemberBudgetPolicyUpdate,
) -> Result<
    models::WorkspaceMemberBudgetPolicyPublic,
    Error<
        UpdateWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesDefaultIdPatchError,
    >,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;
    let p_path_default_id = default_id;
    let p_body_workspace_member_budget_policy_update = workspace_member_budget_policy_update;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/member-budget-policies/{default_id}",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id),
        default_id = crate::apis::urlencode(p_path_default_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };
    req_builder = req_builder.json(&p_body_workspace_member_budget_policy_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceMemberBudgetPolicyPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceMemberBudgetPolicyPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateWorkspaceBudgetDefaultV1WorkspacesWorkspaceIdMemberBudgetPoliciesDefaultIdPatchError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
