/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`clear_workspace_code_execution_policy_v1_workspaces_workspace_id_code_execution_policy_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClearWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyDeleteError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_workspace_code_execution_policy_v1_workspaces_workspace_id_code_execution_policy_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_workspace_code_execution_policy_v1_workspaces_workspace_id_code_execution_policy_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyPutError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// Drop a workspace's policy, returning it to the deployment's behavior.  Idempotent: a workspace that has no policy is already in the state this asks for, so it answers with the unconfigured policy rather than a 404.
pub async fn clear_workspace_code_execution_policy_v1_workspaces_workspace_id_code_execution_policy_delete(
    configuration: &configuration::Configuration,
    workspace_id: &str,
) -> Result<
    models::WorkspaceCodeExecutionPolicyPublic,
    Error<ClearWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyDeleteError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/code-execution-policy",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceCodeExecutionPolicyPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceCodeExecutionPolicyPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<
            ClearWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyDeleteError,
        > = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Read a workspace's code-execution policy.  Takes the same role as setting it (an organization owner/admin, or an owner/admin of this workspace), because the policy describes the workspace's security and billing posture rather than one member's allowance. A workspace with no policy answers with the unconfigured one (``configured: false``), which is the deployment's own behavior described in the same shape rather than a 404.
pub async fn get_workspace_code_execution_policy_v1_workspaces_workspace_id_code_execution_policy_get(
    configuration: &configuration::Configuration,
    workspace_id: &str,
) -> Result<
    models::WorkspaceCodeExecutionPolicyPublic,
    Error<GetWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyGetError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/code-execution-policy",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceCodeExecutionPolicyPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceCodeExecutionPolicyPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<
            GetWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyGetError,
        > = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Set a workspace's code-execution policy, replacing any existing one.  An organization owner/admin, or an owner/admin of this workspace, may write it. The policy can only narrow what the deployment permits: turning code execution off for the workspace, lowering the loop and execution ceilings, and removing tool kinds from what the sandbox backend serves. It never turns a sandbox the deployment has not configured on, and ``image`` may only name one the operator curated (``allowed_images`` on the response reports the set); anything else is refused with 400.
pub async fn set_workspace_code_execution_policy_v1_workspaces_workspace_id_code_execution_policy_put(
    configuration: &configuration::Configuration,
    workspace_id: &str,
    workspace_code_execution_policy_update: models::WorkspaceCodeExecutionPolicyUpdate,
) -> Result<
    models::WorkspaceCodeExecutionPolicyPublic,
    Error<SetWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyPutError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_workspace_id = workspace_id;
    let p_body_workspace_code_execution_policy_update = workspace_code_execution_policy_update;

    let uri_str = format!(
        "{}/v1/workspaces/{workspace_id}/code-execution-policy",
        configuration.base_path,
        workspace_id = crate::apis::urlencode(p_path_workspace_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("x-api-key", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Otari-Key", value);
    };
    req_builder = req_builder.json(&p_body_workspace_code_execution_policy_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WorkspaceCodeExecutionPolicyPublic`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WorkspaceCodeExecutionPolicyPublic`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<
            SetWorkspaceCodeExecutionPolicyV1WorkspacesWorkspaceIdCodeExecutionPolicyPutError,
        > = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
