/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AcceptedSnapshotResponse : One accepted genai-prices snapshot in the history.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcceptedSnapshotResponse {
    #[serde(rename = "accepted_at")]
    pub accepted_at: chrono::DateTime<chrono::FixedOffset>,
    /// `operator` for a dashboard confirm, `schedule` for the auto policy.
    #[serde(rename = "accepted_by")]
    pub accepted_by: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "model_count")]
    pub model_count: i32,
}

impl AcceptedSnapshotResponse {
    /// One accepted genai-prices snapshot in the history.
    pub fn new(
        accepted_at: chrono::DateTime<chrono::FixedOffset>,
        accepted_by: String,
        id: String,
        model_count: i32,
    ) -> AcceptedSnapshotResponse {
        AcceptedSnapshotResponse {
            accepted_at,
            accepted_by,
            id,
            model_count,
        }
    }
}
