/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActiveOrganizationMemberPublic : A member row joined to the identity behind it, as the roster shows it.  Field-for-field the platform's shape, so the ported roster page is not rewritten around a new contract, with two consequences of the OSS line: ``email`` is nullable here (a local operator identity has no sign-in address), and ``invitation_id`` is always null until the invitation flow rehomes, which is what fills it.  ``attribution_user_id`` is the addition the platform has no counterpart for. Keys, budgets, and usage attach to the gateway's string-keyed ``users`` row, not to this UUID identity, so this carries the ``user_id`` a caller passes to ``POST /v1/keys`` to give this member a key. It is null when no usable row exists (nobody minted one, or it was soft-deleted through ``DELETE /v1/users``), which is the signal not to offer this member as a key owner: key creation would refuse. How the two ids converge is the open question in otari-ai#1727; this field is the join until it is answered, and is what lets either answer land without the dashboard changing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActiveOrganizationMemberPublic {
    #[serde(
        rename = "attribution_user_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attribution_user_id: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    #[serde(
        rename = "full_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub full_name: Option<Option<String>>,
    #[serde(
        rename = "invitation_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub invitation_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "organization_member_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_member_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "updated_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "user_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_id: Option<Option<uuid::Uuid>>,
}

impl ActiveOrganizationMemberPublic {
    /// A member row joined to the identity behind it, as the roster shows it.  Field-for-field the platform's shape, so the ported roster page is not rewritten around a new contract, with two consequences of the OSS line: ``email`` is nullable here (a local operator identity has no sign-in address), and ``invitation_id`` is always null until the invitation flow rehomes, which is what fills it.  ``attribution_user_id`` is the addition the platform has no counterpart for. Keys, budgets, and usage attach to the gateway's string-keyed ``users`` row, not to this UUID identity, so this carries the ``user_id`` a caller passes to ``POST /v1/keys`` to give this member a key. It is null when no usable row exists (nobody minted one, or it was soft-deleted through ``DELETE /v1/users``), which is the signal not to offer this member as a key owner: key creation would refuse. How the two ids converge is the open question in otari-ai#1727; this field is the join until it is answered, and is what lets either answer land without the dashboard changing.
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        role: String,
        status: String,
    ) -> ActiveOrganizationMemberPublic {
        ActiveOrganizationMemberPublic {
            attribution_user_id: None,
            created_at,
            email: None,
            full_name: None,
            invitation_id: None,
            organization_member_id: None,
            role,
            status,
            updated_at: None,
            user_id: None,
        }
    }
}
