/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AliasRequest : Request to create or update an alias.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AliasRequest {
    /// Display name callers use as the model, e.g. 'fast-model'.
    #[serde(rename = "name")]
    pub name: String,
    /// Selector the alias resolves to, as 'provider:model' or 'instance:model'.
    #[serde(rename = "target")]
    pub target: String,
    /// User this alias belongs to. Omit for a global alias every caller sees. A user-scoped alias resolves only for that user and shadows a global one of the same name.
    #[serde(
        rename = "user_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_id: Option<Option<String>>,
}

impl AliasRequest {
    /// Request to create or update an alias.
    pub fn new(name: String, target: String) -> AliasRequest {
        AliasRequest {
            name,
            target,
            user_id: None,
        }
    }
}
