/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AliasResponse : A model alias and where it is defined.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AliasResponse {
    #[serde(
        rename = "created_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(
        rename = "updated_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_at: Option<Option<String>>,
    #[serde(
        rename = "user_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_id: Option<Option<String>>,
    #[serde(
        rename = "workspace_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub workspace_id: Option<Option<uuid::Uuid>>,
}

impl AliasResponse {
    /// A model alias and where it is defined.
    pub fn new(name: String, source: String, target: String) -> AliasResponse {
        AliasResponse {
            created_at: None,
            name,
            source,
            target,
            updated_at: None,
            user_id: None,
            workspace_id: None,
        }
    }
}
