/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocationHealthResponse : One set of capped rows, reduced to what a strip renders.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocationHealthResponse {
    /// Rows with a finite cap, which are the ones that can be judged.
    #[serde(rename = "capped_count")]
    pub capped_count: i32,
    /// Rows at 80% of their allowance or more, but not past it.
    #[serde(rename = "near_count")]
    pub near_count: i32,
    /// Rows at or past their allowance.
    #[serde(rename = "over_count")]
    pub over_count: i32,
    /// Rows of any kind, so a caller can tell 'none configured' from 'none caps spend'.
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "worst", deserialize_with = "Option::deserialize")]
    pub worst: Option<Box<models::WorstAllocationResponse>>,
}

impl AllocationHealthResponse {
    /// One set of capped rows, reduced to what a strip renders.
    pub fn new(
        capped_count: i32,
        near_count: i32,
        over_count: i32,
        total_count: i32,
        worst: Option<models::WorstAllocationResponse>,
    ) -> AllocationHealthResponse {
        AllocationHealthResponse {
            capped_count,
            near_count,
            over_count,
            total_count,
            worst: if let Some(x) = worst {
                Some(Box::new(x))
            } else {
                None
            },
        }
    }
}
