/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnthropicFileList : A page of files in Anthropic's list shape, whose cursor is an opaque token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnthropicFileList {
    #[serde(rename = "data")]
    pub data: Vec<models::AnthropicFileMetadata>,
    #[serde(rename = "next_page", deserialize_with = "Option::deserialize")]
    pub next_page: Option<String>,
}

impl AnthropicFileList {
    /// A page of files in Anthropic's list shape, whose cursor is an opaque token.
    pub fn new(
        data: Vec<models::AnthropicFileMetadata>,
        next_page: Option<String>,
    ) -> AnthropicFileList {
        AnthropicFileList { data, next_page }
    }
}
