/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthorizeResponse : Where to send the browser, and the state to check when it comes back.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorizeResponse {
    /// The provider consent screen to navigate to.
    #[serde(rename = "authorization_url")]
    pub authorization_url: String,
    /// An opaque CSRF value to keep for the length of the redirect and compare against the 'state' the provider returns. It is not stored on this deployment, so a callback whose state does not match the one held by the browser that started the flow must be abandoned by the client rather than sent here.
    #[serde(rename = "state")]
    pub state: String,
}

impl AuthorizeResponse {
    /// Where to send the browser, and the state to check when it comes back.
    pub fn new(authorization_url: String, state: String) -> AuthorizeResponse {
        AuthorizeResponse {
            authorization_url,
            state,
        }
    }
}
