/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchInputTokensDetails : A detailed breakdown of the input tokens.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchInputTokensDetails {
    #[serde(rename = "cached_tokens")]
    pub cached_tokens: i32,
}

impl BatchInputTokensDetails {
    /// A detailed breakdown of the input tokens.
    pub fn new(cached_tokens: i32) -> BatchInputTokensDetails {
        BatchInputTokensDetails { cached_tokens }
    }
}
