/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BudgetResetLogResponse : Response model for one budget reset event (per user).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BudgetResetLogResponse {
    #[serde(rename = "budget_id")]
    pub budget_id: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "next_reset_at", deserialize_with = "Option::deserialize")]
    pub next_reset_at: Option<String>,
    #[serde(rename = "previous_spend")]
    pub previous_spend: f64,
    #[serde(rename = "reset_at")]
    pub reset_at: String,
    #[serde(rename = "user_id", deserialize_with = "Option::deserialize")]
    pub user_id: Option<String>,
}

impl BudgetResetLogResponse {
    /// Response model for one budget reset event (per user).
    pub fn new(
        budget_id: String,
        id: i32,
        next_reset_at: Option<String>,
        previous_spend: f64,
        reset_at: String,
        user_id: Option<String>,
    ) -> BudgetResetLogResponse {
        BudgetResetLogResponse {
            budget_id,
            id,
            next_reset_at,
            previous_spend,
            reset_at,
            user_id,
        }
    }
}
