/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CallerIdentityPublic : Who the caller is, as against what they may do.  The account control at the foot of the dashboard's sidebar draws a person, and no authenticated route reported the caller's own name or address, so it drew a role for everybody who could reach it: \"Operator\", which is not a name and on a multi-tenant deployment was not even true (mozilla-ai/otari#832).  Carried on the membership context for the reason ``deployment_operator`` is: the shell reads that context before it paints, so an identity taken from it needs no request of its own and cannot arrive a beat after the chrome it names. Publishing it costs nothing either, since it is the caller's own identity and they are holding the credential that resolved to it.  Both fields are nullable, and for opposite reasons. A local operator identity has no address, because first boot provisions it with a name and nothing to sign in with but the master key; a member added to the roster by address has no name until they claim the identity and supply one. So a shell has to be ready to draw either one alone.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallerIdentityPublic {
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    #[serde(
        rename = "full_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub full_name: Option<Option<String>>,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl CallerIdentityPublic {
    /// Who the caller is, as against what they may do.  The account control at the foot of the dashboard's sidebar draws a person, and no authenticated route reported the caller's own name or address, so it drew a role for everybody who could reach it: \"Operator\", which is not a name and on a multi-tenant deployment was not even true (mozilla-ai/otari#832).  Carried on the membership context for the reason ``deployment_operator`` is: the shell reads that context before it paints, so an identity taken from it needs no request of its own and cannot arrive a beat after the chrome it names. Publishing it costs nothing either, since it is the caller's own identity and they are holding the credential that resolved to it.  Both fields are nullable, and for opposite reasons. A local operator identity has no address, because first boot provisions it with a name and nothing to sign in with but the master key; a member added to the roster by address has no name until they claim the identity and supply one. So a shell has to be ready to draw either one alone.
    pub fn new(user_id: uuid::Uuid) -> CallerIdentityPublic {
        CallerIdentityPublic {
            email: None,
            full_name: None,
            user_id,
        }
    }
}
