/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CallerIdentityPublic : Who the caller is, as against what they may do.  The account control at the foot of the dashboard's sidebar draws a person, and no authenticated route reported the caller's own name or address, so it drew a role for everybody who could reach it: \"Operator\", which is not a name and on a multi-tenant deployment was not even true (mozilla-ai/otari#832).  Carried on the membership context for the reason ``deployment_operator`` is: the shell reads that context before it paints, so an identity taken from it needs no request of its own and cannot arrive a beat after the chrome it names. Publishing it costs nothing either, since it is the caller's own identity and they are holding the credential that resolved to it.  ``email`` and ``full_name`` are nullable for opposite reasons. A local operator identity has no address, because first boot provisions it with a name and nothing to sign in with but the master key; a member added by address has no name until they claim the identity and supply one. So a shell has to be ready to draw either one alone.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallerIdentityPublic {
    /// Whether setting this identity's password claims the deployment, which stops the master key signing in to the dashboard. True for the deployment's operator until it holds a password, whether or not it already has an address; false for everybody else.
    #[serde(rename = "claims_deployment")]
    pub claims_deployment: bool,
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    #[serde(
        rename = "full_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub full_name: Option<Option<String>>,
    /// Whether this identity holds a dashboard password. False for one that signs in only through an OAuth provider or a passkey, and for a roster entry nobody has claimed yet. PUT /api/v1/auth/password requires current_password from a cookie-authenticated caller exactly while this is true.
    #[serde(rename = "has_password")]
    pub has_password: bool,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl CallerIdentityPublic {
    /// Who the caller is, as against what they may do.  The account control at the foot of the dashboard's sidebar draws a person, and no authenticated route reported the caller's own name or address, so it drew a role for everybody who could reach it: \"Operator\", which is not a name and on a multi-tenant deployment was not even true (mozilla-ai/otari#832).  Carried on the membership context for the reason ``deployment_operator`` is: the shell reads that context before it paints, so an identity taken from it needs no request of its own and cannot arrive a beat after the chrome it names. Publishing it costs nothing either, since it is the caller's own identity and they are holding the credential that resolved to it.  ``email`` and ``full_name`` are nullable for opposite reasons. A local operator identity has no address, because first boot provisions it with a name and nothing to sign in with but the master key; a member added by address has no name until they claim the identity and supply one. So a shell has to be ready to draw either one alone.
    pub fn new(
        claims_deployment: bool,
        has_password: bool,
        user_id: uuid::Uuid,
    ) -> CallerIdentityPublic {
        CallerIdentityPublic {
            claims_deployment,
            email: None,
            full_name: None,
            has_password,
            user_id,
        }
    }
}
