/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogVendorFacet {
    /// The vendor's name; empty for models whose vendor is unknown.
    #[serde(rename = "value")]
    pub value: String,
    #[serde(
        rename = "vendor_slug",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub vendor_slug: Option<Option<String>>,
}

impl CatalogVendorFacet {
    pub fn new(value: String) -> CatalogVendorFacet {
        CatalogVendorFacet {
            value,
            vendor_slug: None,
        }
    }
}
