/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.6.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogModelSummary : One model, as the list shows it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogModelSummary {
    #[serde(rename = "capabilities")]
    pub capabilities: Box<models::CatalogCapabilities>,
    /// The largest any offering serves.
    #[serde(
        rename = "context_window",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub context_window: Option<Option<i32>>,
    /// True only when every offering with metadata says so.
    #[serde(rename = "deprecated", skip_serializing_if = "Option::is_none")]
    pub deprecated: Option<bool>,
    /// models.dev's, from the offering that named the model.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Whether any offering was discovered from its provider.
    #[serde(rename = "discovered")]
    pub discovered: bool,
    #[serde(
        rename = "family",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub family: Option<Option<String>>,
    /// The catalog id, vendor-qualified where the vendor is known: `z-ai/glm-5.3`, else the bare slug.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "input_modalities")]
    pub input_modalities: Vec<String>,
    #[serde(
        rename = "knowledge_cutoff",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub knowledge_cutoff: Option<Option<String>>,
    /// The largest any offering serves.
    #[serde(
        rename = "max_output_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_output_tokens: Option<Option<i32>>,
    /// The cheapest offering's, at the comparison context where one was asked for.
    #[serde(
        rename = "min_input_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_input_price_per_million: Option<Option<f64>>,
    #[serde(
        rename = "min_output_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_output_price_per_million: Option<Option<f64>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "offering_count")]
    pub offering_count: i32,
    #[serde(rename = "open_weights", skip_serializing_if = "Option::is_none")]
    pub open_weights: Option<bool>,
    #[serde(rename = "output_modalities")]
    pub output_modalities: Vec<String>,
    /// Which price lists the priced offerings came from, distinct and sorted.
    #[serde(rename = "price_sources")]
    pub price_sources: Vec<PriceSources>,
    #[serde(rename = "provider_count")]
    pub provider_count: i32,
    /// The provider instances offering it, sorted.
    #[serde(rename = "providers")]
    pub providers: Vec<String>,
    #[serde(
        rename = "release_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub release_date: Option<Option<String>>,
    /// The offering `selector` resolves to.
    #[serde(
        rename = "resolves_to",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub resolves_to: Option<Option<String>>,
    /// The id as a selector: send it as `model` and the model's cheapest offering answers. Null until the gateway has indexed the catalog.
    #[serde(
        rename = "selector",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub selector: Option<Option<String>>,
    /// Every offering's selector, so the list can be searched by one.
    #[serde(rename = "selectors")]
    pub selectors: Vec<String>,
    /// How many offerings carry no price for this caller.
    #[serde(rename = "unpriced_count")]
    pub unpriced_count: i32,
    #[serde(rename = "vendor", deserialize_with = "Option::deserialize")]
    pub vendor: Option<String>,
}

impl CatalogModelSummary {
    /// One model, as the list shows it.
    pub fn new(
        capabilities: models::CatalogCapabilities,
        discovered: bool,
        id: String,
        input_modalities: Vec<String>,
        name: String,
        offering_count: i32,
        output_modalities: Vec<String>,
        price_sources: Vec<PriceSources>,
        provider_count: i32,
        providers: Vec<String>,
        selectors: Vec<String>,
        unpriced_count: i32,
        vendor: Option<String>,
    ) -> CatalogModelSummary {
        CatalogModelSummary {
            capabilities: Box::new(capabilities),
            context_window: None,
            deprecated: None,
            description: None,
            discovered,
            family: None,
            id,
            input_modalities,
            knowledge_cutoff: None,
            max_output_tokens: None,
            min_input_price_per_million: None,
            min_output_price_per_million: None,
            name,
            offering_count,
            open_weights: None,
            output_modalities,
            price_sources,
            provider_count,
            providers,
            release_date: None,
            resolves_to: None,
            selector: None,
            selectors,
            unpriced_count,
            vendor,
        }
    }
}
/// Which price lists the priced offerings came from, distinct and sorted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PriceSources {
    #[serde(rename = "organization")]
    Organization,
    #[serde(rename = "deployment")]
    Deployment,
    #[serde(rename = "defaults")]
    Defaults,
}

impl Default for PriceSources {
    fn default() -> PriceSources {
        Self::Organization
    }
}
