/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CcCacheCreationTokenDetails : Cache writes split by time-to-live, as Anthropic reports them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcCacheCreationTokenDetails {
    /// Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
    #[serde(
        rename = "ephemeral_5m_input_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ephemeral_5m_input_tokens: Option<Option<i32>>,
    /// Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
    #[serde(
        rename = "ephemeral_1h_input_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ephemeral_1h_input_tokens: Option<Option<i32>>,
}

impl CcCacheCreationTokenDetails {
    /// Cache writes split by time-to-live, as Anthropic reports them.
    pub fn new() -> CcCacheCreationTokenDetails {
        CcCacheCreationTokenDetails {
            ephemeral_5m_input_tokens: None,
            ephemeral_1h_input_tokens: None,
        }
    }
}
