/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcChatCompletionMessage {
    #[serde(
        rename = "content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content: Option<Option<String>>,
    #[serde(
        rename = "refusal",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refusal: Option<Option<String>>,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(
        rename = "annotations",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub annotations: Option<Option<Vec<std::collections::HashMap<String, serde_json::Value>>>>,
    #[serde(
        rename = "audio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub audio: Option<Option<models::CcChatCompletionAudio>>,
    #[serde(
        rename = "function_call",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub function_call: Option<Option<models::CcFunctionCall>>,
    #[serde(
        rename = "tool_calls",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tool_calls: Option<Option<Vec<models::CcChatCompletionMessageToolCallsInner>>>,
    /// Filter to a single event type or metric name (e.g. 'tool_result', 'claude_code.commit.count')
    #[serde(
        rename = "reasoning",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reasoning: Option<Option<String>>,
    /// Provider-native request fields used as defaults (e.g. exa's 'type', searxng's 'engines').
    #[serde(
        rename = "extra_content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_content: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl CcChatCompletionMessage {
    pub fn new(role: Role) -> CcChatCompletionMessage {
        CcChatCompletionMessage {
            content: None,
            refusal: None,
            role,
            annotations: None,
            audio: None,
            function_call: None,
            tool_calls: None,
            reasoning: None,
            extra_content: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "assistant")]
    Assistant,
}

impl Default for Role {
    fn default() -> Role {
        Self::Assistant
    }
}
