/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CcChatCompletionMessageCustomToolCall : A call to a custom tool created by the model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcChatCompletionMessageCustomToolCall {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "custom")]
    pub custom: models::CcCustom,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl CcChatCompletionMessageCustomToolCall {
    /// A call to a custom tool created by the model.
    pub fn new(
        id: String,
        custom: models::CcCustom,
        r#type: Type,
    ) -> CcChatCompletionMessageCustomToolCall {
        CcChatCompletionMessageCustomToolCall { id, custom, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "custom")]
    Custom,
}

impl Default for Type {
    fn default() -> Type {
        Self::Custom
    }
}
