/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CcPromptTokensDetails : Breakdown of tokens used in the prompt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcPromptTokensDetails {
    #[serde(
        rename = "audio_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub audio_tokens: Option<Option<i32>>,
    /// Filter to a single failure status code (e.g. 429 for provider rate limits, 402 for missing-pricing rejections). Only error rows carry one, so this filter also restricts to status='error' unless 'status' is given explicitly
    #[serde(
        rename = "cached_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cached_tokens: Option<Option<i32>>,
}

impl CcPromptTokensDetails {
    /// Breakdown of tokens used in the prompt.
    pub fn new() -> CcPromptTokensDetails {
        CcPromptTokensDetails {
            audio_tokens: None,
            cached_tokens: None,
        }
    }
}
