/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CckPromptTokensDetails : Breakdown of tokens used in the prompt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CckPromptTokensDetails {
    #[serde(
        rename = "audio_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub audio_tokens: Option<Option<i32>>,
    #[serde(
        rename = "cached_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cached_tokens: Option<Option<i32>>,
}

impl CckPromptTokensDetails {
    /// Breakdown of tokens used in the prompt.
    pub fn new() -> CckPromptTokensDetails {
        CckPromptTokensDetails {
            audio_tokens: None,
            cached_tokens: None,
        }
    }
}
