/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Content4 {
    #[serde(rename = "error_code")]
    pub error_code: ErrorCode,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "stop_reason", skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<String>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "encrypted_content")]
    pub encrypted_content: String,
}

impl Content4 {
    pub fn new(
        error_code: ErrorCode,
        r#type: Type,
        text: String,
        encrypted_content: String,
    ) -> Content4 {
        Content4 {
            error_code,
            r#type,
            stop_reason: None,
            text,
            encrypted_content,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "max_uses_exceeded")]
    MaxUsesExceeded,
    #[serde(rename = "prompt_too_long")]
    PromptTooLong,
    #[serde(rename = "too_many_requests")]
    TooManyRequests,
    #[serde(rename = "overloaded")]
    Overloaded,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "execution_time_exceeded")]
    ExecutionTimeExceeded,
    #[serde(rename = "model_not_found")]
    ModelNotFound,
}

impl Default for ErrorCode {
    fn default() -> ErrorCode {
        Self::MaxUsesExceeded
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "advisor_tool_result_error")]
    AdvisorToolResultError,
    #[serde(rename = "advisor_result")]
    AdvisorResult,
    #[serde(rename = "advisor_redacted_result")]
    AdvisorRedactedResult,
}

impl Default for Type {
    fn default() -> Type {
        Self::AdvisorToolResultError
    }
}
