/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Content13 {
    #[serde(rename = "error_code")]
    pub error_code: ErrorCode,
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "tool_references")]
    pub tool_references: Vec<models::MrToolReferenceBlock>,
}

impl Content13 {
    pub fn new(
        error_code: ErrorCode,
        r#type: Type,
        tool_references: Vec<models::MrToolReferenceBlock>,
    ) -> Content13 {
        Content13 {
            error_code,
            error_message: None,
            r#type,
            tool_references,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "invalid_tool_input")]
    InvalidToolInput,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "too_many_requests")]
    TooManyRequests,
    #[serde(rename = "execution_time_exceeded")]
    ExecutionTimeExceeded,
}

impl Default for ErrorCode {
    fn default() -> ErrorCode {
        Self::InvalidToolInput
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tool_search_tool_result_error")]
    ToolSearchToolResultError,
    #[serde(rename = "tool_search_tool_search_result")]
    ToolSearchToolSearchResult,
}

impl Default for Type {
    fn default() -> Type {
        Self::ToolSearchToolResultError
    }
}
