/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateKeyResponse : Response model for creating a new API key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateKeyResponse {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "expires_at", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "key_name", deserialize_with = "Option::deserialize")]
    pub key_name: Option<String>,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "user_id", deserialize_with = "Option::deserialize")]
    pub user_id: Option<String>,
}

impl CreateKeyResponse {
    /// Response model for creating a new API key.
    pub fn new(
        created_at: String,
        expires_at: Option<String>,
        id: String,
        is_active: bool,
        key: String,
        key_name: Option<String>,
        metadata: std::collections::HashMap<String, serde_json::Value>,
        user_id: Option<String>,
    ) -> CreateKeyResponse {
        CreateKeyResponse {
            created_at,
            expires_at,
            id,
            is_active,
            key,
            key_name,
            metadata,
            user_id,
        }
    }
}
