/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateBudgetRequest : Request model for creating a new budget.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBudgetRequest {
    /// Budget duration in seconds (e.g., 86400 for daily, 604800 for weekly)
    #[serde(
        rename = "budget_duration_sec",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub budget_duration_sec: Option<Option<i32>>,
    /// Maximum spending limit
    #[serde(
        rename = "max_budget",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_budget: Option<Option<f64>>,
}

impl CreateBudgetRequest {
    /// Request model for creating a new budget.
    pub fn new() -> CreateBudgetRequest {
        CreateBudgetRequest {
            budget_duration_sec: None,
            max_budget: None,
        }
    }
}
