/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateOwnKeyRequest : Create-key body for the member surface.  Deliberately not ``CreateKeyRequest``: it carries no ``user_id`` (the owner is always the caller) and no ``exclude_from_budget`` (a member must not exempt their own spend from enforcement).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOwnKeyRequest {
    /// Model allow-list: null = any model your user default allows, [] = deny all, or canonical instance:model entries. A key can only narrow your own model access, never broaden it.
    #[serde(
        rename = "allowed_models",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_models: Option<Option<Vec<String>>>,
    /// Per-key override of the deployment-wide capture_agent_telemetry setting: null (default) inherits it, true always stores this key's coding-agent telemetry, false always discards it.
    #[serde(
        rename = "capture_agent_telemetry",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub capture_agent_telemetry: Option<Option<bool>>,
    /// Optional expiration timestamp
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Optional name for the key
    #[serde(
        rename = "key_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub key_name: Option<Option<String>>,
    /// Optional metadata
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Per-key override of the deployment-wide reject_user_mismatch setting: null (default) inherits it, true always rejects a request naming a different 'user', false always accepts it. Spend binds to your own user either way.
    #[serde(
        rename = "reject_user_mismatch",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reject_user_mismatch: Option<Option<bool>>,
    /// Workspace this key belongs to, which must be one you may see in your active organization. Omitted means that organization's default workspace, refused when you are not a member of it.
    #[serde(
        rename = "workspace_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub workspace_id: Option<Option<uuid::Uuid>>,
}

impl CreateOwnKeyRequest {
    /// Create-key body for the member surface.  Deliberately not ``CreateKeyRequest``: it carries no ``user_id`` (the owner is always the caller) and no ``exclude_from_budget`` (a member must not exempt their own spend from enforcement).
    pub fn new() -> CreateOwnKeyRequest {
        CreateOwnKeyRequest {
            allowed_models: None,
            capture_agent_telemetry: None,
            expires_at: None,
            key_name: None,
            metadata: None,
            reject_user_mismatch: None,
            workspace_id: None,
        }
    }
}
