/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateUserRequest : Request model for creating a new user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserRequest {
    /// Optional admin-facing alias
    #[serde(
        rename = "alias",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub alias: Option<Option<String>>,
    /// Default model access-list this user's keys inherit; null = unrestricted, [] = deny all
    #[serde(
        rename = "allowed_models",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_models: Option<Option<Vec<String>>>,
    /// Whether user is blocked
    #[serde(rename = "blocked", skip_serializing_if = "Option::is_none")]
    pub blocked: Option<bool>,
    /// Optional budget ID
    #[serde(
        rename = "budget_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub budget_id: Option<Option<String>>,
    /// Optional metadata
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Unique user identifier
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl CreateUserRequest {
    /// Request model for creating a new user.
    pub fn new(user_id: String) -> CreateUserRequest {
        CreateUserRequest {
            alias: None,
            allowed_models: None,
            blocked: None,
            budget_id: None,
            metadata: None,
            user_id,
        }
    }
}
