/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentUserOrganizationPublic : One organization an identity belongs to, as the operator surface lists it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentUserOrganizationPublic {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "organization_id")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl DeploymentUserOrganizationPublic {
    /// One organization an identity belongs to, as the operator surface lists it.
    pub fn new(
        name: String,
        organization_id: uuid::Uuid,
        role: String,
        slug: String,
        status: String,
    ) -> DeploymentUserOrganizationPublic {
        DeploymentUserOrganizationPublic {
            name,
            organization_id,
            role,
            slug,
            status,
        }
    }
}
