/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoverableModelsResponse : Per-provider discovery results for operator model selection.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoverableModelsResponse {
    #[serde(rename = "providers")]
    pub providers: Vec<models::DiscoverableProvider>,
}

impl DiscoverableModelsResponse {
    /// Per-provider discovery results for operator model selection.
    pub fn new(providers: Vec<models::DiscoverableProvider>) -> DiscoverableModelsResponse {
        DiscoverableModelsResponse { providers }
    }
}
