/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscoverableModel : A model one provider instance reports as available.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoverableModel {
    /// Bare model id as the provider reports it.
    #[serde(rename = "id")]
    pub id: String,
    /// Selector to send as `model`, in `instance:model` form.
    #[serde(rename = "key")]
    pub key: String,
}

impl DiscoverableModel {
    /// A model one provider instance reports as available.
    pub fn new(id: String, key: String) -> DiscoverableModel {
        DiscoverableModel { id, key }
    }
}
