/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmbUsage : The usage information for the request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbUsage {
    #[serde(rename = "prompt_tokens")]
    pub prompt_tokens: i32,
    #[serde(rename = "total_tokens")]
    pub total_tokens: i32,
}

impl EmbUsage {
    /// The usage information for the request.
    pub fn new(prompt_tokens: i32, total_tokens: i32) -> EmbUsage {
        EmbUsage {
            prompt_tokens,
            total_tokens,
        }
    }
}
