/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EndUserPublic : An end user of a service key, addressed by the id the service named it by.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndUserPublic {
    #[serde(rename = "blocked")]
    pub blocked: bool,
    #[serde(rename = "budget_id", deserialize_with = "Option::deserialize")]
    pub budget_id: Option<String>,
    #[serde(rename = "budget_started_at", deserialize_with = "Option::deserialize")]
    pub budget_started_at: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "current_requests")]
    pub current_requests: i32,
    #[serde(rename = "current_tokens")]
    pub current_tokens: i32,
    #[serde(rename = "external_id")]
    pub external_id: String,
    #[serde(
        rename = "next_budget_reset_at",
        deserialize_with = "Option::deserialize"
    )]
    pub next_budget_reset_at: Option<String>,
    #[serde(rename = "owner_user_id")]
    pub owner_user_id: String,
    #[serde(rename = "reserved")]
    pub reserved: f64,
    #[serde(rename = "spend")]
    pub spend: f64,
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl EndUserPublic {
    /// An end user of a service key, addressed by the id the service named it by.
    pub fn new(
        blocked: bool,
        budget_id: Option<String>,
        budget_started_at: Option<String>,
        created_at: String,
        current_requests: i32,
        current_tokens: i32,
        external_id: String,
        next_budget_reset_at: Option<String>,
        owner_user_id: String,
        reserved: f64,
        spend: f64,
        user_id: String,
    ) -> EndUserPublic {
        EndUserPublic {
            blocked,
            budget_id,
            budget_started_at,
            created_at,
            current_requests,
            current_tokens,
            external_id,
            next_budget_reset_at,
            owner_user_id,
            reserved,
            spend,
            user_id,
        }
    }
}
