/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExplainResponse : The plan a policy compiles to for the given inputs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExplainResponse {
    #[serde(rename = "candidates")]
    pub candidates: Vec<models::CandidateResponse>,
    #[serde(rename = "dropped")]
    pub dropped: Vec<models::DroppedResponse>,
    #[serde(rename = "guardrails")]
    pub guardrails: Vec<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "is_dynamic")]
    pub is_dynamic: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "selection_reason")]
    pub selection_reason: String,
}

impl ExplainResponse {
    /// The plan a policy compiles to for the given inputs.
    pub fn new(
        candidates: Vec<models::CandidateResponse>,
        dropped: Vec<models::DroppedResponse>,
        guardrails: Vec<std::collections::HashMap<String, serde_json::Value>>,
        is_dynamic: bool,
        name: String,
        selection_reason: String,
    ) -> ExplainResponse {
        ExplainResponse {
            candidates,
            dropped,
            guardrails,
            is_dynamic,
            name,
            selection_reason,
        }
    }
}
