/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExternalIngestError : A single rejected event, with enough context to fix it and retry.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalIngestError {
    #[serde(rename = "detail")]
    pub detail: String,
    #[serde(rename = "index")]
    pub index: i32,
    #[serde(rename = "source_event_id", deserialize_with = "Option::deserialize")]
    pub source_event_id: Option<String>,
}

impl ExternalIngestError {
    /// A single rejected event, with enough context to fix it and retry.
    pub fn new(detail: String, index: i32, source_event_id: Option<String>) -> ExternalIngestError {
        ExternalIngestError {
            detail,
            index,
            source_event_id,
        }
    }
}
