/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.6.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GuardrailCatalog : The profiles a guardrail entry may name, or why they could not be listed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuardrailCatalog {
    /// Whether the guardrails service answered with its profiles
    #[serde(rename = "available")]
    pub available: bool,
    #[serde(rename = "profiles", skip_serializing_if = "Option::is_none")]
    pub profiles: Option<Vec<models::GuardrailProfileSpec>>,
    /// Why the catalog is unavailable, in terms a tenant can act on
    #[serde(
        rename = "reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reason: Option<Option<String>>,
}

impl GuardrailCatalog {
    /// The profiles a guardrail entry may name, or why they could not be listed.
    pub fn new(available: bool) -> GuardrailCatalog {
        GuardrailCatalog {
            available,
            profiles: None,
            reason: None,
        }
    }
}
