/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImgUsageOutputTokensDetails : The output token details for the image generation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImgUsageOutputTokensDetails {
    #[serde(rename = "image_tokens")]
    pub image_tokens: i32,
    #[serde(rename = "text_tokens")]
    pub text_tokens: i32,
}

impl ImgUsageOutputTokensDetails {
    /// The output token details for the image generation.
    pub fn new(image_tokens: i32, text_tokens: i32) -> ImgUsageOutputTokensDetails {
        ImgUsageOutputTokensDetails {
            image_tokens,
            text_tokens,
        }
    }
}
