/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImgImage : Represents the content or the URL of an image generated by the OpenAI API.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImgImage {
    /// Filter to a single event type or metric name (e.g. 'tool_result', 'claude_code.commit.count')
    #[serde(
        rename = "b64_json",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub b64_json: Option<Option<String>>,
    /// Filter to a single event type or metric name (e.g. 'tool_result', 'claude_code.commit.count')
    #[serde(
        rename = "revised_prompt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub revised_prompt: Option<Option<String>>,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl ImgImage {
    /// Represents the content or the URL of an image generated by the OpenAI API.
    pub fn new() -> ImgImage {
        ImgImage {
            b64_json: None,
            revised_prompt: None,
            url: None,
        }
    }
}
