/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InFlightResponse : The requests in flight on the answering worker.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InFlightResponse {
    #[serde(rename = "requests")]
    pub requests: Vec<models::InFlightEntry>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl InFlightResponse {
    /// The requests in flight on the answering worker.
    pub fn new(requests: Vec<models::InFlightEntry>, total: i32) -> InFlightResponse {
        InFlightResponse { requests, total }
    }
}
