/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Input1 : Text, list of texts, or list of content-part dicts to moderate
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Input1 {}

impl Input1 {
    /// Text, list of texts, or list of content-part dicts to moderate
    pub fn new() -> Input1 {
        Input1 {}
    }
}
