/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MaintenanceMode : Whether this deployment is currently refusing new dashboard sign-ins.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaintenanceMode {
    /// When true, POST /v1/auth/session refuses every credential with 503 so nobody starts a new dashboard session during a redeploy. Sessions already issued keep working, and the management API and the data plane are unaffected: a caller presenting the master key or an API key through the header is never frozen out.
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl MaintenanceMode {
    /// Whether this deployment is currently refusing new dashboard sign-ins.
    pub fn new(enabled: bool) -> MaintenanceMode {
        MaintenanceMode { enabled }
    }
}
