/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MemberAttributionPublic : What the gateway identity behind a membership has spent, and may reach.  Deployment-wide facts, so they are withheld from a caller who does not operate the deployment rather than zeroed: ``/api/v1/users`` refuses them, and a zero here would read as a member who has spent nothing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberAttributionPublic {
    #[serde(
        rename = "allowed_models",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_models: Option<Option<Vec<String>>>,
    #[serde(rename = "blocked")]
    pub blocked: bool,
    #[serde(rename = "reserved")]
    pub reserved: f64,
    #[serde(rename = "spend")]
    pub spend: f64,
}

impl MemberAttributionPublic {
    /// What the gateway identity behind a membership has spent, and may reach.  Deployment-wide facts, so they are withheld from a caller who does not operate the deployment rather than zeroed: ``/api/v1/users`` refuses them, and a zero here would read as a member who has spent nothing.
    pub fn new(blocked: bool, reserved: f64, spend: f64) -> MemberAttributionPublic {
        MemberAttributionPublic {
            allowed_models: None,
            blocked,
            reserved,
            spend,
        }
    }
}
