/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelMetadata : models.dev metadata for one model, for the dashboard's detail view.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelMetadata {
    #[serde(rename = "attachment", skip_serializing_if = "Option::is_none")]
    pub attachment: Option<bool>,
    #[serde(
        rename = "context_window",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub context_window: Option<Option<i32>>,
    #[serde(
        rename = "cost_input",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cost_input: Option<Option<f64>>,
    #[serde(
        rename = "cost_output",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cost_output: Option<Option<f64>>,
    #[serde(rename = "deprecated", skip_serializing_if = "Option::is_none")]
    pub deprecated: Option<bool>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(
        rename = "family",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub family: Option<Option<String>>,
    #[serde(rename = "input_modalities", skip_serializing_if = "Option::is_none")]
    pub input_modalities: Option<Vec<String>>,
    #[serde(
        rename = "knowledge_cutoff",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub knowledge_cutoff: Option<Option<String>>,
    #[serde(
        rename = "last_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_updated: Option<Option<String>>,
    #[serde(
        rename = "max_output_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_output_tokens: Option<Option<i32>>,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    #[serde(rename = "open_weights", skip_serializing_if = "Option::is_none")]
    pub open_weights: Option<bool>,
    #[serde(rename = "output_modalities", skip_serializing_if = "Option::is_none")]
    pub output_modalities: Option<Vec<String>>,
    #[serde(rename = "reasoning", skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<bool>,
    #[serde(
        rename = "release_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub release_date: Option<Option<String>>,
    #[serde(rename = "structured_output", skip_serializing_if = "Option::is_none")]
    pub structured_output: Option<bool>,
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<bool>,
    #[serde(rename = "tool_call", skip_serializing_if = "Option::is_none")]
    pub tool_call: Option<bool>,
}

impl ModelMetadata {
    /// models.dev metadata for one model, for the dashboard's detail view.
    pub fn new() -> ModelMetadata {
        ModelMetadata {
            attachment: None,
            context_window: None,
            cost_input: None,
            cost_output: None,
            deprecated: None,
            description: None,
            family: None,
            input_modalities: None,
            knowledge_cutoff: None,
            last_updated: None,
            max_output_tokens: None,
            name: None,
            open_weights: None,
            output_modalities: None,
            reasoning: None,
            release_date: None,
            structured_output: None,
            temperature: None,
            tool_call: None,
        }
    }
}
