/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelPricingInfo : Pricing information for a model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelPricingInfo {
    #[serde(rename = "input_price_per_million")]
    pub input_price_per_million: f64,
    #[serde(rename = "output_price_per_million")]
    pub output_price_per_million: f64,
}

impl ModelPricingInfo {
    /// Pricing information for a model.
    pub fn new(input_price_per_million: f64, output_price_per_million: f64) -> ModelPricingInfo {
        ModelPricingInfo {
            input_price_per_million,
            output_price_per_million,
        }
    }
}
