/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaCacheMissPreviousMessageNotFound {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrBetaCacheMissPreviousMessageNotFound {
    pub fn new(r#type: Type) -> MrBetaCacheMissPreviousMessageNotFound {
        MrBetaCacheMissPreviousMessageNotFound { r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "previous_message_not_found")]
    PreviousMessageNotFound,
}

impl Default for Type {
    fn default() -> Type {
        Self::PreviousMessageNotFound
    }
}
