/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaCacheMissToolsChanged {
    #[serde(rename = "cache_missed_input_tokens")]
    pub cache_missed_input_tokens: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrBetaCacheMissToolsChanged {
    pub fn new(cache_missed_input_tokens: i32, r#type: Type) -> MrBetaCacheMissToolsChanged {
        MrBetaCacheMissToolsChanged {
            cache_missed_input_tokens,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tools_changed")]
    ToolsChanged,
}

impl Default for Type {
    fn default() -> Type {
        Self::ToolsChanged
    }
}
