/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MrBetaCompactionBlock : A compaction block returned when autocompact is triggered.  When content is None, it indicates the compaction failed to produce a valid summary (e.g., malformed output from the model). Clients may round-trip compaction blocks with null content; the server treats them as no-ops.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaCompactionBlock {
    #[serde(
        rename = "content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content: Option<Option<String>>,
    /// Filter to a single event type or metric name (e.g. 'tool_result', 'claude_code.commit.count')
    #[serde(
        rename = "encrypted_content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub encrypted_content: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrBetaCompactionBlock {
    /// A compaction block returned when autocompact is triggered.  When content is None, it indicates the compaction failed to produce a valid summary (e.g., malformed output from the model). Clients may round-trip compaction blocks with null content; the server treats them as no-ops.
    pub fn new(r#type: Type) -> MrBetaCompactionBlock {
        MrBetaCompactionBlock {
            content: None,
            encrypted_content: None,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "compaction")]
    Compaction,
}

impl Default for Type {
    fn default() -> Type {
        Self::Compaction
    }
}
