/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaCitationConfig {
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl MrBetaCitationConfig {
    pub fn new(enabled: bool) -> MrBetaCitationConfig {
        MrBetaCitationConfig { enabled }
    }
}
