/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaContextManagementResponse {
    #[serde(rename = "applied_edits")]
    pub applied_edits: Vec<models::AppliedEditsInner>,
}

impl MrBetaContextManagementResponse {
    pub fn new(applied_edits: Vec<models::AppliedEditsInner>) -> MrBetaContextManagementResponse {
        MrBetaContextManagementResponse { applied_edits }
    }
}
