/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MrBetaFallbackBlock : Marks the point in `content` where one model's output gives way to the next.  One block appears per hop where a preceding model actually ran this turn and declined. A turn where no preceding model ran and declined has no such boundary and carries no block — the signal for whether a fallback model served the response is the presence of a `fallback_message` entry in `usage.iterations`, not this block.  The block is treated like a server-tool content block for streaming: it arrives via the standard `content_block_start` / `content_block_stop` pair and carries no deltas.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaFallbackBlock {
    #[serde(rename = "from")]
    pub from: models::MrBetaFallbackInfo,
    #[serde(rename = "to")]
    pub to: models::MrBetaFallbackInfo,
    #[serde(rename = "trigger")]
    pub trigger: models::MrBetaFallbackRefusalTrigger,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrBetaFallbackBlock {
    /// Marks the point in `content` where one model's output gives way to the next.  One block appears per hop where a preceding model actually ran this turn and declined. A turn where no preceding model ran and declined has no such boundary and carries no block — the signal for whether a fallback model served the response is the presence of a `fallback_message` entry in `usage.iterations`, not this block.  The block is treated like a server-tool content block for streaming: it arrives via the standard `content_block_start` / `content_block_stop` pair and carries no deltas.
    pub fn new(
        from: models::MrBetaFallbackInfo,
        to: models::MrBetaFallbackInfo,
        trigger: models::MrBetaFallbackRefusalTrigger,
        r#type: Type,
    ) -> MrBetaFallbackBlock {
        MrBetaFallbackBlock {
            from,
            to,
            trigger,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "fallback")]
    Fallback,
}

impl Default for Type {
    fn default() -> Type {
        Self::Fallback
    }
}
