/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaThinkingBlock {
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "thinking")]
    pub thinking: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrBetaThinkingBlock {
    pub fn new(signature: String, thinking: String, r#type: Type) -> MrBetaThinkingBlock {
        MrBetaThinkingBlock {
            signature,
            thinking,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "thinking")]
    Thinking,
}

impl Default for Type {
    fn default() -> Type {
        Self::Thinking
    }
}
