/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MrBetaContainer : Information about the container used in the request (for the code execution tool)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaContainer {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "expires_at")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(
        rename = "skills",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub skills: Option<Option<Vec<models::MrBetaSkill>>>,
}

impl MrBetaContainer {
    /// Information about the container used in the request (for the code execution tool)
    pub fn new(id: String, expires_at: chrono::DateTime<chrono::FixedOffset>) -> MrBetaContainer {
        MrBetaContainer {
            id,
            expires_at,
            skills: None,
        }
    }
}
