/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrBetaBashCodeExecutionOutputBlock {
    #[serde(rename = "file_id")]
    pub file_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrBetaBashCodeExecutionOutputBlock {
    pub fn new(file_id: String, r#type: Type) -> MrBetaBashCodeExecutionOutputBlock {
        MrBetaBashCodeExecutionOutputBlock { file_id, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "bash_code_execution_output")]
    BashCodeExecutionOutput,
}

impl Default for Type {
    fn default() -> Type {
        Self::BashCodeExecutionOutput
    }
}
