/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MrContainerUploadBlock : Response model for a file uploaded to the container.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrContainerUploadBlock {
    #[serde(rename = "file_id")]
    pub file_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrContainerUploadBlock {
    /// Response model for a file uploaded to the container.
    pub fn new(file_id: String, r#type: Type) -> MrContainerUploadBlock {
        MrContainerUploadBlock { file_id, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "container_upload")]
    ContainerUpload,
}

impl Default for Type {
    fn default() -> Type {
        Self::ContainerUpload
    }
}
