/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrServerToolCaller20260120 {
    #[serde(rename = "tool_id")]
    pub tool_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrServerToolCaller20260120 {
    pub fn new(tool_id: String, r#type: Type) -> MrServerToolCaller20260120 {
        MrServerToolCaller20260120 { tool_id, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "code_execution_20260120")]
    CodeExecution20260120,
}

impl Default for Type {
    fn default() -> Type {
        Self::CodeExecution20260120
    }
}
