/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrTextBlockCitationsInner {
    #[serde(rename = "cited_text")]
    pub cited_text: String,
    #[serde(rename = "document_index")]
    pub document_index: i32,
    #[serde(rename = "document_title", skip_serializing_if = "Option::is_none")]
    pub document_title: Option<String>,
    #[serde(rename = "end_char_index")]
    pub end_char_index: i32,
    #[serde(rename = "file_id", skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
    #[serde(rename = "start_char_index")]
    pub start_char_index: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "end_page_number")]
    pub end_page_number: i32,
    #[serde(rename = "start_page_number")]
    pub start_page_number: i32,
    #[serde(rename = "end_block_index")]
    pub end_block_index: i32,
    #[serde(rename = "start_block_index")]
    pub start_block_index: i32,
    #[serde(rename = "encrypted_index")]
    pub encrypted_index: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "search_result_index")]
    pub search_result_index: i32,
    #[serde(rename = "source")]
    pub source: String,
}

impl MrTextBlockCitationsInner {
    pub fn new(
        cited_text: String,
        document_index: i32,
        end_char_index: i32,
        start_char_index: i32,
        r#type: Type,
        end_page_number: i32,
        start_page_number: i32,
        end_block_index: i32,
        start_block_index: i32,
        encrypted_index: String,
        url: String,
        search_result_index: i32,
        source: String,
    ) -> MrTextBlockCitationsInner {
        MrTextBlockCitationsInner {
            cited_text,
            document_index,
            document_title: None,
            end_char_index,
            file_id: None,
            start_char_index,
            r#type,
            end_page_number,
            start_page_number,
            end_block_index,
            start_block_index,
            encrypted_index,
            title: None,
            url,
            search_result_index,
            source,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "char_location")]
    CharLocation,
    #[serde(rename = "page_location")]
    PageLocation,
    #[serde(rename = "content_block_location")]
    ContentBlockLocation,
    #[serde(rename = "web_search_result_location")]
    WebSearchResultLocation,
    #[serde(rename = "search_result_location")]
    SearchResultLocation,
}

impl Default for Type {
    fn default() -> Type {
        Self::CharLocation
    }
}
