/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrToolReferenceBlock {
    #[serde(rename = "tool_name")]
    pub tool_name: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MrToolReferenceBlock {
    pub fn new(tool_name: String, r#type: Type) -> MrToolReferenceBlock {
        MrToolReferenceBlock { tool_name, r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tool_reference")]
    ToolReference,
}

impl Default for Type {
    fn default() -> Type {
        Self::ToolReference
    }
}
