/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrWebFetchBlock {
    #[serde(rename = "content")]
    pub content: models::MrDocumentBlock,
    /// Filter models by provider name
    #[serde(
        rename = "retrieved_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub retrieved_at: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "url")]
    pub url: String,
}

impl MrWebFetchBlock {
    pub fn new(content: models::MrDocumentBlock, r#type: Type, url: String) -> MrWebFetchBlock {
        MrWebFetchBlock {
            content,
            retrieved_at: None,
            r#type,
            url,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "web_fetch_result")]
    WebFetchResult,
}

impl Default for Type {
    fn default() -> Type {
        Self::WebFetchResult
    }
}
