/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OpenAiFileObject : One file in OpenAI's file object shape.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenAiFileObject {
    #[serde(rename = "bytes")]
    pub bytes: i32,
    #[serde(rename = "created_at")]
    pub created_at: i32,
    #[serde(rename = "expires_at", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<i32>,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Object>,
    #[serde(rename = "purpose")]
    pub purpose: String,
}

impl OpenAiFileObject {
    /// One file in OpenAI's file object shape.
    pub fn new(
        bytes: i32,
        created_at: i32,
        expires_at: Option<i32>,
        filename: String,
        id: String,
        purpose: String,
    ) -> OpenAiFileObject {
        OpenAiFileObject {
            bytes,
            created_at,
            expires_at,
            filename,
            id,
            object: None,
            purpose,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "file")]
    File,
}

impl Default for Object {
    fn default() -> Object {
        Self::File
    }
}
