/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrgProviderKeyModelUpdateRequest : Whether the runtime serves this model. The only field an update may change.  A rate is not here: an organization's rates live in ``organization_model_pricing`` and are written through ``/organizations/me/pricing``, so a price set on this surface and a price set on that one could not disagree.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgProviderKeyModelUpdateRequest {
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl OrgProviderKeyModelUpdateRequest {
    /// Whether the runtime serves this model. The only field an update may change.  A rate is not here: an organization's rates live in ``organization_model_pricing`` and are written through ``/organizations/me/pricing``, so a price set on this surface and a price set on that one could not disagree.
    pub fn new(enabled: bool) -> OrgProviderKeyModelUpdateRequest {
        OrgProviderKeyModelUpdateRequest { enabled }
    }
}
