/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrgProviderKeyModelCreateRequest : Offer one model on a key, for a backend whose models cannot be listed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgProviderKeyModelCreateRequest {
    #[serde(rename = "model")]
    pub model: String,
}

impl OrgProviderKeyModelCreateRequest {
    /// Offer one model on a key, for a backend whose models cannot be listed.
    pub fn new(model: String) -> OrgProviderKeyModelCreateRequest {
        OrgProviderKeyModelCreateRequest { model }
    }
}
