/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrgProviderKeyUpdateRequest : A partial update. Every field is optional; only what is set is applied.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgProviderKeyUpdateRequest {
    #[serde(
        rename = "api_base",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_base: Option<Option<String>>,
    #[serde(
        rename = "api_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_key: Option<Option<String>>,
    #[serde(
        rename = "client_args",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_args: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
}

impl OrgProviderKeyUpdateRequest {
    /// A partial update. Every field is optional; only what is set is applied.
    pub fn new() -> OrgProviderKeyUpdateRequest {
        OrgProviderKeyUpdateRequest {
            api_base: None,
            api_key: None,
            client_args: None,
            name: None,
        }
    }
}
