/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationScopedBudgetsPublic {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "data")]
    pub data: Vec<models::OrganizationScopedBudgetPublic>,
}

impl OrganizationScopedBudgetsPublic {
    pub fn new(
        count: i32,
        data: Vec<models::OrganizationScopedBudgetPublic>,
    ) -> OrganizationScopedBudgetsPublic {
        OrganizationScopedBudgetsPublic { count, data }
    }
}
