/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrganizationGuardrailTest : Text to run one mandate's check over, as a request would.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationGuardrailTest {
    /// The input to check, as a request's user text would reach it
    #[serde(rename = "text")]
    pub text: String,
    /// Per-check arguments to send in place of the stored ones; omitted sends the stored ones. A *** keeps the value stored under that name
    #[serde(rename = "validate_kwargs", skip_serializing_if = "Option::is_none")]
    pub validate_kwargs: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl OrganizationGuardrailTest {
    /// Text to run one mandate's check over, as a request would.
    pub fn new(text: String) -> OrganizationGuardrailTest {
        OrganizationGuardrailTest {
            text,
            validate_kwargs: None,
        }
    }
}
