/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrganizationGuardrailDefinitionUpdate : Partial update. Only the fields the caller sets are applied.  ``create_kwargs`` replaces the arguments whole when sent, and an argument the catalog marks secret keeps its stored value where the caller echoes back the ``***`` a read gave them. Omitting it leaves both columns untouched *and reads neither*, which is what lets an admin on a deployment whose ``OTARI_SECRET_KEY`` has moved still flip ``enabled`` and repair the row by typing the credential again.  Changing ``guardrail_name`` without sending ``create_kwargs`` re-splits the stored arguments under the new class, because the plain/secret split is the old class's answer and would otherwise go stale.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationGuardrailDefinitionUpdate {
    /// Tags for cost attribution, recorded on the request's usage rows and filterable in the usage API: up to 16 string pairs, keys up to 64 characters and values up to 512. A null value is ignored. LiteLLM's nested `spend_logs_metadata` object is also read, and wins over a flat key of the same name; it is never forwarded to the provider.
    #[serde(
        rename = "create_kwargs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub create_kwargs: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "guardrail_name", skip_serializing_if = "Option::is_none")]
    pub guardrail_name: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl OrganizationGuardrailDefinitionUpdate {
    /// Partial update. Only the fields the caller sets are applied.  ``create_kwargs`` replaces the arguments whole when sent, and an argument the catalog marks secret keeps its stored value where the caller echoes back the ``***`` a read gave them. Omitting it leaves both columns untouched *and reads neither*, which is what lets an admin on a deployment whose ``OTARI_SECRET_KEY`` has moved still flip ``enabled`` and repair the row by typing the credential again.  Changing ``guardrail_name`` without sending ``create_kwargs`` re-splits the stored arguments under the new class, because the plain/secret split is the old class's answer and would otherwise go stale.
    pub fn new() -> OrganizationGuardrailDefinitionUpdate {
        OrganizationGuardrailDefinitionUpdate {
            create_kwargs: None,
            enabled: None,
            guardrail_name: None,
            name: None,
        }
    }
}
