/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrganizationModelPricingUpdate : Replace an override's rates and period.  ``effective_from`` is required here, where a create defaults it to now. A replacement states the whole row, so defaulting an omitted start would move a stored period to the present: an operator editing next quarter's rate through a client that does not send the field would silently bring it into effect today, or collide with the period that currently applies. Stating it is the only reading that cannot surprise.  A full replacement rather than a patch: every rate field is present in the body and an omitted optional rate is cleared, so the stored row is exactly what was sent. That is the opposite of ``POST /v1/pricing``, which inherits an omitted cache rate from the model's previous version, and deliberately so: that surface versions a catalog where each write adds a row, while this one edits a single row in place and an inheriting patch would make the result depend on what happened to be stored before.  ``model_key`` is absent because it is immutable. Repointing an override at another model is retiring one and creating another, which is two requests.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationModelPricingUpdate {
    /// Price per 1M cached-input tokens
    #[serde(
        rename = "cache_read_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_read_price_per_million: Option<Option<f64>>,
    /// Price per 1M Anthropic 1-hour cache-write tokens
    #[serde(
        rename = "cache_write_1h_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_write_1h_price_per_million: Option<Option<f64>>,
    /// Price per 1M cache-write (creation) tokens
    #[serde(
        rename = "cache_write_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_write_price_per_million: Option<Option<f64>>,
    /// ISO 8601 datetime from which this rate applies, inclusive. Required on a replacement, so an omitted value cannot silently move a stored period to the present.
    #[serde(rename = "effective_from")]
    pub effective_from: chrono::DateTime<chrono::FixedOffset>,
    /// ISO 8601 datetime at which this rate stops applying, exclusive. Null leaves it open ended. Because the end is exclusive, the next period may begin at exactly this instant without overlapping.
    #[serde(
        rename = "effective_to",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub effective_to: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Price per 1M input tokens
    #[serde(rename = "input_price_per_million")]
    pub input_price_per_million: f64,
    /// Price per 1M output tokens
    #[serde(rename = "output_price_per_million")]
    pub output_price_per_million: f64,
    /// Whole-request context thresholds. Fields omitted by a tier inherit the base rate.
    #[serde(
        rename = "pricing_tiers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pricing_tiers: Option<Option<Vec<models::PricingTier>>>,
}

impl OrganizationModelPricingUpdate {
    /// Replace an override's rates and period.  ``effective_from`` is required here, where a create defaults it to now. A replacement states the whole row, so defaulting an omitted start would move a stored period to the present: an operator editing next quarter's rate through a client that does not send the field would silently bring it into effect today, or collide with the period that currently applies. Stating it is the only reading that cannot surprise.  A full replacement rather than a patch: every rate field is present in the body and an omitted optional rate is cleared, so the stored row is exactly what was sent. That is the opposite of ``POST /v1/pricing``, which inherits an omitted cache rate from the model's previous version, and deliberately so: that surface versions a catalog where each write adds a row, while this one edits a single row in place and an inheriting patch would make the result depend on what happened to be stored before.  ``model_key`` is absent because it is immutable. Repointing an override at another model is retiring one and creating another, which is two requests.
    pub fn new(
        effective_from: chrono::DateTime<chrono::FixedOffset>,
        input_price_per_million: f64,
        output_price_per_million: f64,
    ) -> OrganizationModelPricingUpdate {
        OrganizationModelPricingUpdate {
            cache_read_price_per_million: None,
            cache_write_1h_price_per_million: None,
            cache_write_price_per_million: None,
            effective_from,
            effective_to: None,
            input_price_per_million,
            output_price_per_million,
            pricing_tiers: None,
        }
    }
}
