/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.6.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OutputShape : The decision form a guardrail produces (aligns with the populated ``GuardrailOutput`` fields).  ``SCORE`` and ``RUBRIC`` are also the queryable signal for whether ``GuardrailOutput.score`` can ever be populated: a guardrail declaring **neither** always leaves ``score`` as ``None`` (it only emits a categorical/binary verdict, not a calibrated risk value). A guardrail declaring **either** populates ``score`` in the common, successfully-parsed case, but individual guardrails may still leave it ``None`` in specific edge cases (e.g. a fail-closed parse-failure path, or a guardrail that flags something but has nothing to score) — consult the guardrail's own docstring for those exceptions.
/// The decision form a guardrail produces (aligns with the populated ``GuardrailOutput`` fields).  ``SCORE`` and ``RUBRIC`` are also the queryable signal for whether ``GuardrailOutput.score`` can ever be populated: a guardrail declaring **neither** always leaves ``score`` as ``None`` (it only emits a categorical/binary verdict, not a calibrated risk value). A guardrail declaring **either** populates ``score`` in the common, successfully-parsed case, but individual guardrails may still leave it ``None`` in specific edge cases (e.g. a fail-closed parse-failure path, or a guardrail that flags something but has nothing to score) — consult the guardrail's own docstring for those exceptions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OutputShape {
    #[serde(rename = "binary")]
    Binary,
    #[serde(rename = "multi_label")]
    MultiLabel,
    #[serde(rename = "categorical")]
    Categorical,
    #[serde(rename = "score")]
    Score,
    #[serde(rename = "rubric")]
    Rubric,
    #[serde(rename = "span")]
    Span,
}

impl std::fmt::Display for OutputShape {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Binary => write!(f, "binary"),
            Self::MultiLabel => write!(f, "multi_label"),
            Self::Categorical => write!(f, "categorical"),
            Self::Score => write!(f, "score"),
            Self::Rubric => write!(f, "rubric"),
            Self::Span => write!(f, "span"),
        }
    }
}

impl Default for OutputShape {
    fn default() -> OutputShape {
        Self::Binary
    }
}
