/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.6.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlaygroundMessageCreate : One turn in a transcript being saved.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaygroundMessageCreate {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(
        rename = "reasoning",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reasoning: Option<Option<String>>,
    #[serde(rename = "role")]
    pub role: Role,
}

impl PlaygroundMessageCreate {
    /// One turn in a transcript being saved.
    pub fn new(content: String, role: Role) -> PlaygroundMessageCreate {
        PlaygroundMessageCreate {
            content,
            reasoning: None,
            role,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
}

impl Default for Role {
    fn default() -> Role {
        Self::User
    }
}
