/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlaygroundFavoriteModelsUpdate : The whole pin list, replacing whatever was stored.  A replace rather than a toggle endpoint, because the client already holds the list it is rendering and the order is part of it (a newly pinned model leads). Two tabs racing therefore resolve to one of the two lists rather than to an interleaving neither of them showed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaygroundFavoriteModelsUpdate {
    #[serde(rename = "model_keys")]
    pub model_keys: Vec<String>,
}

impl PlaygroundFavoriteModelsUpdate {
    /// The whole pin list, replacing whatever was stored.  A replace rather than a toggle endpoint, because the client already holds the list it is rendering and the order is part of it (a newly pinned model leads). Two tabs racing therefore resolve to one of the two lists rather than to an interleaving neither of them showed.
    pub fn new(model_keys: Vec<String>) -> PlaygroundFavoriteModelsUpdate {
        PlaygroundFavoriteModelsUpdate { model_keys }
    }
}
