/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.6.4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlaygroundToolsResponse : What the caller's workspace may attach to a Playground message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaygroundToolsResponse {
    #[serde(rename = "code_execution")]
    pub code_execution: Box<models::PlaygroundToolStatus>,
    #[serde(rename = "mcp_servers")]
    pub mcp_servers: Vec<models::PlaygroundMcpServer>,
    #[serde(rename = "web_search")]
    pub web_search: Box<models::PlaygroundToolStatus>,
}

impl PlaygroundToolsResponse {
    /// What the caller's workspace may attach to a Playground message.
    pub fn new(
        code_execution: models::PlaygroundToolStatus,
        mcp_servers: Vec<models::PlaygroundMcpServer>,
        web_search: models::PlaygroundToolStatus,
    ) -> PlaygroundToolsResponse {
        PlaygroundToolsResponse {
            code_execution: Box::new(code_execution),
            mcp_servers,
            web_search: Box::new(web_search),
        }
    }
}
