/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PolicyCheckRequest : A policy body plus the evidence to check it against, both caller-supplied.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyCheckRequest {
    /// Verifier verdicts the caller collected for this request's verifier gates.
    #[serde(
        rename = "check_results",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_results: Option<Option<Vec<models::CheckVerdictRequest>>>,
    /// What `commands` covers: `call` for the single tool call about to run, `session` for every command the session has run so far.
    #[serde(rename = "command_scope", skip_serializing_if = "Option::is_none")]
    pub command_scope: Option<CommandScope>,
    /// Shell commands the caller observed run or is about to run.
    #[serde(
        rename = "commands",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub commands: Option<Option<Vec<String>>>,
    /// Model verdicts the caller collected for this request's judge gates.
    #[serde(
        rename = "judge_results",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub judge_results: Option<Option<Vec<models::JudgeVerdictRequest>>>,
    /// Which moment `paths` was read at, matching the `runs` values a path gate declares. Only three of the six `runs` values are legal here, because only those three are moments a path can be read at: `pre_tool_use.edit_target` for a write tool's own target before it runs, `pre_tool_use.read_target` for a read tool's, and `stop.working_tree` for `git status` once the turn is over. Required whenever `paths` is non-empty, and rejected with a 422 if omitted or set to any other value: either would resolve every path gate `not_applicable`, which loses enforcement without reporting anything. An empty `paths` needs no source.
    #[serde(
        rename = "path_source",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub path_source: Option<Option<PathSource>>,
    /// Repo-relative paths this moment of the session puts in scope: what `git status --porcelain` reports, or the single target a tool call is about to write or read. `path_source` says which.
    #[serde(
        rename = "paths",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub paths: Option<Option<Vec<String>>>,
    #[serde(rename = "policy_yaml")]
    pub policy_yaml: String,
}

impl PolicyCheckRequest {
    /// A policy body plus the evidence to check it against, both caller-supplied.
    pub fn new(policy_yaml: String) -> PolicyCheckRequest {
        PolicyCheckRequest {
            check_results: None,
            command_scope: None,
            commands: None,
            judge_results: None,
            path_source: None,
            paths: None,
            policy_yaml,
        }
    }
}
/// What `commands` covers: `call` for the single tool call about to run, `session` for every command the session has run so far.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CommandScope {
    #[serde(rename = "call")]
    Call,
    #[serde(rename = "session")]
    Session,
}

impl Default for CommandScope {
    fn default() -> CommandScope {
        Self::Call
    }
}
/// Which moment `paths` was read at, matching the `runs` values a path gate declares. Only three of the six `runs` values are legal here, because only those three are moments a path can be read at: `pre_tool_use.edit_target` for a write tool's own target before it runs, `pre_tool_use.read_target` for a read tool's, and `stop.working_tree` for `git status` once the turn is over. Required whenever `paths` is non-empty, and rejected with a 422 if omitted or set to any other value: either would resolve every path gate `not_applicable`, which loses enforcement without reporting anything. An empty `paths` needs no source.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PathSource {
    #[serde(rename = "pre_tool_use.edit_target")]
    PreToolUseEditTarget,
    #[serde(rename = "pre_tool_use.read_target")]
    PreToolUseReadTarget,
    #[serde(rename = "pre_tool_use.command")]
    PreToolUseCommand,
    #[serde(rename = "stop.working_tree")]
    StopWorkingTree,
    #[serde(rename = "stop.session")]
    StopSession,
    #[serde(rename = "stop.verifier")]
    StopVerifier,
}

impl Default for PathSource {
    fn default() -> PathSource {
        Self::PreToolUseEditTarget
    }
}
