/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PricingTier : Whole-request price cliff selected by total billable input tokens.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PricingTier {
    #[serde(
        rename = "cache_read_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_read_price_per_million: Option<Option<f64>>,
    #[serde(
        rename = "cache_write_1h_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_write_1h_price_per_million: Option<Option<f64>>,
    #[serde(
        rename = "cache_write_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cache_write_price_per_million: Option<Option<f64>>,
    #[serde(
        rename = "input_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_price_per_million: Option<Option<f64>>,
    #[serde(rename = "min_input_tokens")]
    pub min_input_tokens: i32,
    #[serde(
        rename = "output_price_per_million",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub output_price_per_million: Option<Option<f64>>,
}

impl PricingTier {
    /// Whole-request price cliff selected by total billable input tokens.
    pub fn new(min_input_tokens: i32) -> PricingTier {
        PricingTier {
            cache_read_price_per_million: None,
            cache_write_1h_price_per_million: None,
            cache_write_price_per_million: None,
            input_price_per_million: None,
            min_input_tokens,
            output_price_per_million: None,
        }
    }
}
