/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProvidersResponse : Metadata for every configured provider.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvidersResponse {
    #[serde(rename = "providers")]
    pub providers: Vec<models::ProviderInfoSchema>,
}

impl ProvidersResponse {
    /// Metadata for every configured provider.
    pub fn new(providers: Vec<models::ProviderInfoSchema>) -> ProvidersResponse {
        ProvidersResponse { providers }
    }
}
