/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum QuestionsValue {
    #[serde(rename = "noul")]
    Noul(models::NoulQuestion),
    #[serde(rename = "choice")]
    Choice(models::ChoiceQuestion),
    #[serde(rename = "score")]
    Score(models::ScoreQuestion),
}

impl Default for QuestionsValue {
    fn default() -> Self {
        Self::Noul(Default::default())
    }
}
