/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RankResponse {
    #[serde(rename = "pools")]
    pub pools: Vec<models::RecordedPool>,
    #[serde(rename = "recorded")]
    pub recorded: i32,
    #[serde(rename = "seed_count")]
    pub seed_count: i32,
}

impl RankResponse {
    pub fn new(pools: Vec<models::RecordedPool>, recorded: i32, seed_count: i32) -> RankResponse {
        RankResponse {
            pools,
            recorded,
            seed_count,
        }
    }
}
