/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RateLimitRuleCreate : A rule to add. The same fields, limits and validation as a ``rate_limits`` entry in config.yml.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitRuleCreate {
    /// How long a max_concurrent slot is held at most. A slot is given back when its response ends; this bounds what a process that dies mid-request keeps.
    #[serde(rename = "lease_sec", skip_serializing_if = "Option::is_none")]
    pub lease_sec: Option<f64>,
    /// Requests in flight at once.
    #[serde(
        rename = "max_concurrent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_concurrent: Option<Option<i32>>,
    /// The models a `per: model` rule limits, each as instance:model (the provider instance the model is called through, then the model), each counted on its own. Required there and refused on any other rule.
    #[serde(
        rename = "models",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub models: Option<Option<Vec<String>>>,
    /// Names the rule in a 429's detail and in the counter's key. Unique across rate_limits.
    #[serde(rename = "name")]
    pub name: String,
    /// What one count is shared by.
    #[serde(rename = "per")]
    pub per: Per,
    /// Requests per minute.
    #[serde(
        rename = "rpm",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rpm: Option<Option<i32>>,
    /// Tokens per minute, counted on what each request used; see tpm_admission for how a request is admitted.
    #[serde(
        rename = "tpm",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tpm: Option<Option<i32>>,
    /// How a tpm limit admits a request. 'used' (the default) admits a request while the minute's tokens are under the limit and counts what it used once it completes, as LiteLLM does. 'estimate' holds the request's estimate (prompt plus max output, or budget_estimate_default_output_tokens) while it runs and refuses it when that does not fit, which is how providers count their own quotas: use it for a limit meant to stay under one.
    #[serde(rename = "tpm_admission", skip_serializing_if = "Option::is_none")]
    pub tpm_admission: Option<TpmAdmission>,
}

impl RateLimitRuleCreate {
    /// A rule to add. The same fields, limits and validation as a ``rate_limits`` entry in config.yml.
    pub fn new(name: String, per: Per) -> RateLimitRuleCreate {
        RateLimitRuleCreate {
            lease_sec: None,
            max_concurrent: None,
            models: None,
            name,
            per,
            rpm: None,
            tpm: None,
            tpm_admission: None,
        }
    }
}
/// What one count is shared by.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Per {
    #[serde(rename = "deployment")]
    Deployment,
    #[serde(rename = "key")]
    Key,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "model")]
    Model,
}

impl Default for Per {
    fn default() -> Per {
        Self::Deployment
    }
}
/// How a tpm limit admits a request. 'used' (the default) admits a request while the minute's tokens are under the limit and counts what it used once it completes, as LiteLLM does. 'estimate' holds the request's estimate (prompt plus max output, or budget_estimate_default_output_tokens) while it runs and refuses it when that does not fit, which is how providers count their own quotas: use it for a limit meant to stay under one.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TpmAdmission {
    #[serde(rename = "used")]
    Used,
    #[serde(rename = "estimate")]
    Estimate,
}

impl Default for TpmAdmission {
    fn default() -> TpmAdmission {
        Self::Used
    }
}
