/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegisterPasskeyRequest : A completed registration ceremony, with the label to file it under.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterPasskeyRequest {
    /// The browser's PublicKeyCredential, serialized.
    #[serde(rename = "credential")]
    pub credential: std::collections::HashMap<String, serde_json::Value>,
    /// What to call this passkey in the credential list. Optional: an unnamed one is numbered rather than refused, so a browser that offers no prompt still works.
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
}

impl RegisterPasskeyRequest {
    /// A completed registration ceremony, with the label to file it under.
    pub fn new(
        credential: std::collections::HashMap<String, serde_json::Value>,
    ) -> RegisterPasskeyRequest {
        RegisterPasskeyRequest {
            credential,
            name: None,
        }
    }
}
