/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RerankResponse : Normalized rerank response, provider-agnostic.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RerankResponse {
    /// Delete the alias scoped to this user. Omit to delete the global alias of that name.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    /// Results sorted by relevance_score descending
    #[serde(rename = "results")]
    pub results: Vec<models::RrRerankResult>,
    #[serde(
        rename = "meta",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub meta: Option<Option<Box<models::RrRerankMeta>>>,
    #[serde(
        rename = "usage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub usage: Option<Option<Box<models::RrRerankUsage>>>,
}

impl RerankResponse {
    /// Normalized rerank response, provider-agnostic.
    pub fn new(results: Vec<models::RrRerankResult>) -> RerankResponse {
        RerankResponse {
            id: None,
            results,
            meta: None,
            usage: None,
        }
    }
}
