/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResendVerificationRequest {
    /// The address to resend a verification link to.
    #[serde(rename = "email")]
    pub email: String,
}

impl ResendVerificationRequest {
    pub fn new(email: String) -> ResendVerificationRequest {
        ResendVerificationRequest { email }
    }
}
