/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseFilesCreateFile {
    #[serde(rename = "bytes")]
    pub bytes: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "expires_at")]
    pub expires_at: String,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Object>,
    #[serde(rename = "purpose")]
    pub purpose: String,
    #[serde(rename = "downloadable", skip_serializing_if = "Option::is_none")]
    pub downloadable: Option<Downloadable>,
    #[serde(rename = "mime_type")]
    pub mime_type: String,
    #[serde(rename = "size_bytes")]
    pub size_bytes: i32,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl ResponseFilesCreateFile {
    pub fn new(
        bytes: i32,
        created_at: String,
        expires_at: String,
        filename: String,
        id: String,
        purpose: String,
        mime_type: String,
        size_bytes: i32,
    ) -> ResponseFilesCreateFile {
        ResponseFilesCreateFile {
            bytes,
            created_at,
            expires_at,
            filename,
            id,
            object: None,
            purpose,
            downloadable: None,
            mime_type,
            size_bytes,
            r#type: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "file")]
    File,
}

impl Default for Object {
    fn default() -> Object {
        Self::File
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Downloadable {
    #[serde(rename = "true")]
    True,
}

impl Default for Downloadable {
    fn default() -> Downloadable {
        Self::True
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}
