/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseFilesListFiles {
    #[serde(rename = "data")]
    pub data: Vec<models::AnthropicFileMetadata>,
    #[serde(rename = "first_id")]
    pub first_id: String,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "last_id")]
    pub last_id: String,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Object>,
    #[serde(rename = "next_page")]
    pub next_page: String,
}

impl ResponseFilesListFiles {
    pub fn new(
        data: Vec<models::AnthropicFileMetadata>,
        first_id: String,
        has_more: bool,
        last_id: String,
        next_page: String,
    ) -> ResponseFilesListFiles {
        ResponseFilesListFiles {
            data,
            first_id,
            has_more,
            last_id,
            object: None,
            next_page,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "list")]
    List,
}

impl Default for Object {
    fn default() -> Object {
        Self::List
    }
}
