/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchToolTestRequest : An unsaved search or fetch instance to test, and what to test it with.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchToolTestRequest {
    /// Backend endpoint. Omit to inherit the provider's default (searxng inherits web_search_url).
    #[serde(
        rename = "api_base",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_base: Option<Option<String>>,
    /// Provider API key. Stored encrypted; never returned.
    #[serde(
        rename = "api_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_key: Option<Option<String>>,
    /// For a search instance: the fetch instance that enriches its results, a configured or stored one or builtin_fetch. Omit it for the fetch default.
    #[serde(
        rename = "fetch_tool",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fetch_tool: Option<Option<String>>,
    /// 'search' or 'fetch'. It cannot change once created.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<Kind>,
    /// Name callers pass as 'search_tool_name' or in /api/v1/search/{tool}, or that names a fetch instance. It contains no '/' or ':', is not builtin_fetch or none in any case, and is unique across search and fetch instances.
    #[serde(rename = "name")]
    pub name: String,
    /// Provider-native request fields used as defaults (e.g. exa's 'type', searxng's 'engines').
    #[serde(
        rename = "options",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub options: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Provider id. GET /api/v1/search-tools/providers lists the search providers, and with ?kind=fetch the fetch providers.
    #[serde(rename = "provider")]
    pub provider: String,
    /// For a search instance: the query to run.
    #[serde(
        rename = "query",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub query: Option<Option<String>>,
    /// Per-request timeout in seconds.
    #[serde(
        rename = "timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout: Option<Option<f64>>,
    /// For a fetch instance: the page to fetch.
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
}

impl SearchToolTestRequest {
    /// An unsaved search or fetch instance to test, and what to test it with.
    pub fn new(name: String, provider: String) -> SearchToolTestRequest {
        SearchToolTestRequest {
            api_base: None,
            api_key: None,
            fetch_tool: None,
            kind: None,
            name,
            options: None,
            provider,
            query: None,
            timeout: None,
            url: None,
        }
    }
}
/// 'search' or 'fetch'. It cannot change once created.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "search")]
    Search,
    #[serde(rename = "fetch")]
    Fetch,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Search
    }
}
