/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SelectorIndexResponse : What the rebuilt index knows.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectorIndexResponse {
    /// Slugs that resolve to an offering.
    #[serde(rename = "models")]
    pub models: i32,
    /// Selectors the deployment serves.
    #[serde(rename = "offerings")]
    pub offerings: i32,
    /// Pinned spellings, one per instance a model is offered on.
    #[serde(rename = "pinned_selectors")]
    pub pinned_selectors: i32,
}

impl SelectorIndexResponse {
    /// What the rebuilt index knows.
    pub fn new(models: i32, offerings: i32, pinned_selectors: i32) -> SelectorIndexResponse {
        SelectorIndexResponse {
            models,
            offerings,
            pinned_selectors,
        }
    }
}
