/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SessionResponse : A freshly minted dashboard session (the token travels only in the cookie).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionResponse {
    /// When the session cookie stops being accepted.
    #[serde(rename = "expires_at")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SessionResponse {
    /// A freshly minted dashboard session (the token travels only in the cookie).
    pub fn new(expires_at: chrono::DateTime<chrono::FixedOffset>) -> SessionResponse {
        SessionResponse { expires_at }
    }
}
