/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SetPricingRequest : Request model for setting model pricing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetPricingRequest {
    /// ISO 8601 datetime from which this price applies. Defaults to now if omitted.
    #[serde(
        rename = "effective_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub effective_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Price per 1M input tokens
    #[serde(rename = "input_price_per_million")]
    pub input_price_per_million: f64,
    /// Model identifier in format 'provider:model'
    #[serde(rename = "model_key")]
    pub model_key: String,
    /// Price per 1M output tokens
    #[serde(rename = "output_price_per_million")]
    pub output_price_per_million: f64,
}

impl SetPricingRequest {
    /// Request model for setting model pricing.
    pub fn new(
        input_price_per_million: f64,
        model_key: String,
        output_price_per_million: f64,
    ) -> SetPricingRequest {
        SetPricingRequest {
            effective_at: None,
            input_price_per_million,
            model_key,
            output_price_per_million,
        }
    }
}
