/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StoredSearchToolSchema : A runtime-stored search tool. The API key is never returned, only ``last4``.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoredSearchToolSchema {
    #[serde(
        rename = "api_base",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_base: Option<Option<String>>,
    #[serde(
        rename = "created_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<String>>,
    #[serde(rename = "decryptable", skip_serializing_if = "Option::is_none")]
    pub decryptable: Option<bool>,
    #[serde(
        rename = "last4",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last4: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "provider")]
    pub provider: String,
    /// True when a config-file search tool of the same name exists; the stored one is in effect.
    #[serde(rename = "shadows_config", skip_serializing_if = "Option::is_none")]
    pub shadows_config: Option<bool>,
    #[serde(
        rename = "timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout: Option<Option<f64>>,
    #[serde(
        rename = "updated_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_at: Option<Option<String>>,
}

impl StoredSearchToolSchema {
    /// A runtime-stored search tool. The API key is never returned, only ``last4``.
    pub fn new(name: String, provider: String) -> StoredSearchToolSchema {
        StoredSearchToolSchema {
            api_base: None,
            created_at: None,
            decryptable: None,
            last4: None,
            name,
            options: None,
            provider,
            shadows_config: None,
            timeout: None,
            updated_at: None,
        }
    }
}
