/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestServiceResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl TestServiceResponse {
    pub fn new(ok: bool, reason: String) -> TestServiceResponse {
        TestServiceResponse { ok, reason }
    }
}
