/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ToolSettingField : One editable tool/guardrail field surfaced to the dashboard.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolSettingField {
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "service")]
    pub service: Service,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<Box<models::Value1>>,
}

impl ToolSettingField {
    /// One editable tool/guardrail field surfaced to the dashboard.
    pub fn new(
        key: String,
        service: Service,
        r#type: Type,
        value: Option<models::Value1>,
    ) -> ToolSettingField {
        ToolSettingField {
            description: None,
            key,
            service,
            r#type,
            value: if let Some(x) = value {
                Some(Box::new(x))
            } else {
                None
            },
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Service {
    #[serde(rename = "web_search")]
    WebSearch,
    #[serde(rename = "sandbox")]
    Sandbox,
    #[serde(rename = "guardrails")]
    Guardrails,
}

impl Default for Service {
    fn default() -> Service {
        Self::WebSearch
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "str")]
    Str,
    #[serde(rename = "int")]
    Int,
    #[serde(rename = "bool")]
    Bool,
}

impl Default for Type {
    fn default() -> Type {
        Self::Url
    }
}
