/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnitChargeLine : A charge line billed per call, for gateway-run tools and per-request routes.  ``unit_rate`` is the discriminator, in the same sense as :class:`TokenChargeLine`'s ``rate_per_million``.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnitChargeLine {
    /// USD charged for this line.
    #[serde(rename = "cost")]
    pub cost: f64,
    /// What was metered, e.g. 'request' or 'web_search_calls'.
    #[serde(rename = "meter")]
    pub meter: String,
    /// USD per call.
    #[serde(rename = "unit_rate")]
    pub unit_rate: f64,
    #[serde(rename = "units")]
    pub units: Box<models::Units1>,
}

impl UnitChargeLine {
    /// A charge line billed per call, for gateway-run tools and per-request routes.  ``unit_rate`` is the discriminator, in the same sense as :class:`TokenChargeLine`'s ``rate_per_million``.
    pub fn new(cost: f64, meter: String, unit_rate: f64, units: models::Units1) -> UnitChargeLine {
        UnitChargeLine {
            cost,
            meter,
            unit_rate,
            units: Box::new(units),
        }
    }
}
