/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateScopedBudgetRequest : Request model for updating a scoped budget.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateScopedBudgetRequest {
    #[serde(
        rename = "budget_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub budget_id: Option<Option<String>>,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
}

impl UpdateScopedBudgetRequest {
    /// Request model for updating a scoped budget.
    pub fn new() -> UpdateScopedBudgetRequest {
        UpdateScopedBudgetRequest {
            budget_id: None,
            name: None,
        }
    }
}
