/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateUserRequest : Request model for updating a user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserRequest {
    #[serde(
        rename = "alias",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub alias: Option<Option<String>>,
    #[serde(
        rename = "blocked",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blocked: Option<Option<bool>>,
    #[serde(
        rename = "budget_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub budget_id: Option<Option<String>>,
    #[serde(
        rename = "metadata",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl UpdateUserRequest {
    /// Request model for updating a user.
    pub fn new() -> UpdateUserRequest {
        UpdateUserRequest {
            alias: None,
            blocked: None,
            budget_id: None,
            metadata: None,
        }
    }
}
