/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateBudgetRequest : Request model for updating a budget.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBudgetRequest {
    #[serde(
        rename = "budget_duration_sec",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub budget_duration_sec: Option<Option<i32>>,
    #[serde(
        rename = "max_budget",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_budget: Option<Option<f64>>,
}

impl UpdateBudgetRequest {
    /// Request model for updating a budget.
    pub fn new() -> UpdateBudgetRequest {
        UpdateBudgetRequest {
            budget_duration_sec: None,
            max_budget: None,
        }
    }
}
