/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateToolSettingsRequest : Change one or more tool settings. Omitted fields are left unchanged; an explicit ``null`` clears a field back to the configured env/YAML default.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateToolSettingsRequest {
    #[serde(
        rename = "guardrails_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub guardrails_url: Option<Option<String>>,
    #[serde(
        rename = "sandbox_purpose_hint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sandbox_purpose_hint: Option<Option<String>>,
    #[serde(
        rename = "sandbox_session_image",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sandbox_session_image: Option<Option<String>>,
    #[serde(
        rename = "sandbox_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sandbox_url: Option<Option<String>>,
    #[serde(
        rename = "web_search_engines",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub web_search_engines: Option<Option<String>>,
    #[serde(
        rename = "web_search_extract",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub web_search_extract: Option<Option<bool>>,
    #[serde(
        rename = "web_search_intercept",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub web_search_intercept: Option<Option<bool>>,
    #[serde(
        rename = "web_search_max_results",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub web_search_max_results: Option<Option<i32>>,
    #[serde(
        rename = "web_search_purpose_hint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub web_search_purpose_hint: Option<Option<String>>,
    #[serde(
        rename = "web_search_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub web_search_url: Option<Option<String>>,
}

impl UpdateToolSettingsRequest {
    /// Change one or more tool settings. Omitted fields are left unchanged; an explicit ``null`` clears a field back to the configured env/YAML default.
    pub fn new() -> UpdateToolSettingsRequest {
        UpdateToolSettingsRequest {
            guardrails_url: None,
            sandbox_purpose_hint: None,
            sandbox_session_image: None,
            sandbox_url: None,
            web_search_engines: None,
            web_search_extract: None,
            web_search_intercept: None,
            web_search_max_results: None,
            web_search_purpose_hint: None,
            web_search_url: None,
        }
    }
}
