/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UsageGroupedSeries : A per-group time series for the dashboard's stacked charts.  ``groups`` ranks the window's top groups by spend (plus the reconciling ``other`` fold), in the order a chart should stack and color them; ``points`` is sparse (only populated cells), keyed by canonical UTC ``bucket_start``.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageGroupedSeries {
    #[serde(rename = "bucket")]
    pub bucket: Bucket,
    #[serde(rename = "end_date")]
    pub end_date: String,
    #[serde(rename = "group_by")]
    pub group_by: GroupBy,
    #[serde(rename = "groups")]
    pub groups: Vec<models::UsageGroupRow>,
    #[serde(rename = "points")]
    pub points: Vec<models::UsageGroupedSeriesPoint>,
    #[serde(rename = "start_date")]
    pub start_date: String,
}

impl UsageGroupedSeries {
    /// A per-group time series for the dashboard's stacked charts.  ``groups`` ranks the window's top groups by spend (plus the reconciling ``other`` fold), in the order a chart should stack and color them; ``points`` is sparse (only populated cells), keyed by canonical UTC ``bucket_start``.
    pub fn new(
        bucket: Bucket,
        end_date: String,
        group_by: GroupBy,
        groups: Vec<models::UsageGroupRow>,
        points: Vec<models::UsageGroupedSeriesPoint>,
        start_date: String,
    ) -> UsageGroupedSeries {
        UsageGroupedSeries {
            bucket,
            end_date,
            group_by,
            groups,
            points,
            start_date,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Bucket {
    #[serde(rename = "hour")]
    Hour,
    #[serde(rename = "day")]
    Day,
}

impl Default for Bucket {
    fn default() -> Bucket {
        Self::Hour
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupBy {
    #[serde(rename = "model")]
    Model,
    #[serde(rename = "user_id")]
    UserId,
    #[serde(rename = "api_key_id")]
    ApiKeyId,
    #[serde(rename = "source")]
    Source,
}

impl Default for GroupBy {
    fn default() -> GroupBy {
        Self::Model
    }
}
