/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UsageSeriesPoint : One time bucket. ``bucket_start`` is canonical ISO-8601 UTC (``...Z``), identical across SQLite and PostgreSQL for the same underlying instant.  ``tokens`` stays the raw provider-reported total (the field predates the composition split and external consumers may read it). The billed composition fields are normalized via billing meters (see ``_billed_expr``): ``input_tokens`` includes both cache buckets, so a chart derives fresh input as ``max(0, input_tokens - cache_read_tokens - cache_write_tokens)`` and the billed total as ``fresh + cache_read + cache_write + output``.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageSeriesPoint {
    #[serde(rename = "bucket_start")]
    pub bucket_start: String,
    #[serde(rename = "cache_read_tokens", skip_serializing_if = "Option::is_none")]
    pub cache_read_tokens: Option<i32>,
    #[serde(rename = "cache_write_tokens", skip_serializing_if = "Option::is_none")]
    pub cache_write_tokens: Option<i32>,
    #[serde(rename = "cost")]
    pub cost: f64,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<i32>,
    #[serde(rename = "input_tokens", skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<i32>,
    #[serde(rename = "output_tokens", skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<i32>,
    #[serde(rename = "requests")]
    pub requests: i32,
    #[serde(rename = "tokens")]
    pub tokens: i32,
}

impl UsageSeriesPoint {
    /// One time bucket. ``bucket_start`` is canonical ISO-8601 UTC (``...Z``), identical across SQLite and PostgreSQL for the same underlying instant.  ``tokens`` stays the raw provider-reported total (the field predates the composition split and external consumers may read it). The billed composition fields are normalized via billing meters (see ``_billed_expr``): ``input_tokens`` includes both cache buckets, so a chart derives fresh input as ``max(0, input_tokens - cache_read_tokens - cache_write_tokens)`` and the billed total as ``fresh + cache_read + cache_write + output``.
    pub fn new(bucket_start: String, cost: f64, requests: i32, tokens: i32) -> UsageSeriesPoint {
        UsageSeriesPoint {
            bucket_start,
            cache_read_tokens: None,
            cache_write_tokens: None,
            cost,
            errors: None,
            input_tokens: None,
            output_tokens: None,
            requests,
            tokens,
        }
    }
}
