/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebAuthnCredentialPublic : A passkey as the settings page lists it.  Carries no key material. ``credential_id`` is here because the browser needs it to tell the passkey it just used from the others in the list, and it is a public identifier the authenticator hands to any site that asks: it is what ``allowCredentials`` publishes to an unauthenticated caller during a ceremony.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebAuthnCredentialPublic {
    #[serde(rename = "backed_up")]
    pub backed_up: bool,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "credential_id")]
    pub credential_id: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_usable")]
    pub is_usable: bool,
    #[serde(rename = "last_used_at", deserialize_with = "Option::deserialize")]
    pub last_used_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "rp_id")]
    pub rp_id: String,
    #[serde(rename = "transports")]
    pub transports: Vec<String>,
}

impl WebAuthnCredentialPublic {
    /// A passkey as the settings page lists it.  Carries no key material. ``credential_id`` is here because the browser needs it to tell the passkey it just used from the others in the list, and it is a public identifier the authenticator hands to any site that asks: it is what ``allowCredentials`` publishes to an unauthenticated caller during a ceremony.
    pub fn new(
        backed_up: bool,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        credential_id: String,
        id: uuid::Uuid,
        is_usable: bool,
        last_used_at: Option<chrono::DateTime<chrono::FixedOffset>>,
        name: String,
        rp_id: String,
        transports: Vec<String>,
    ) -> WebAuthnCredentialPublic {
        WebAuthnCredentialPublic {
            backed_up,
            created_at,
            credential_id,
            id,
            is_usable,
            last_used_at,
            name,
            rp_id,
            transports,
        }
    }
}
