/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceMcpServerPublic : The API-facing shape. Never carries the token, only whether one is set.  No ``last4``-style prefix either, unlike `OrgProviderKeyPublic`: a provider key's last four digits let an operator match a stored key against the one in their provider's console, and there is no equivalent workflow for an MCP bearer token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceMcpServerPublic {
    #[serde(rename = "allowed_tools", deserialize_with = "Option::deserialize")]
    pub allowed_tools: Option<Vec<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "has_token")]
    pub has_token: bool,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "purpose_hint", deserialize_with = "Option::deserialize")]
    pub purpose_hint: Option<String>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "workspace_id")]
    pub workspace_id: uuid::Uuid,
}

impl WorkspaceMcpServerPublic {
    /// The API-facing shape. Never carries the token, only whether one is set.  No ``last4``-style prefix either, unlike `OrgProviderKeyPublic`: a provider key's last four digits let an operator match a stored key against the one in their provider's console, and there is no equivalent workflow for an MCP bearer token.
    pub fn new(
        allowed_tools: Option<Vec<String>>,
        created_at: String,
        enabled: bool,
        has_token: bool,
        id: uuid::Uuid,
        name: String,
        purpose_hint: Option<String>,
        updated_at: String,
        url: String,
        workspace_id: uuid::Uuid,
    ) -> WorkspaceMcpServerPublic {
        WorkspaceMcpServerPublic {
            allowed_tools,
            created_at,
            enabled,
            has_token,
            id,
            name,
            purpose_hint,
            updated_at,
            url,
            workspace_id,
        }
    }
}
