/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceMcpServerUpdate : Partial update. Only the fields the caller sets are applied.  ``authorization_token`` has three states rather than two, which is what a write-only field needs: omit it to leave the stored token alone, send ``\"\"`` to clear it, send a value to rotate it. An explicit ``null`` also leaves it alone, matching the platform: a client that serializes its whole form back, with an empty token box it never filled in, must not destroy a token it was never shown.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceMcpServerUpdate {
    #[serde(
        rename = "allowed_tools",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_tools: Option<Option<Vec<String>>>,
    #[serde(
        rename = "authorization_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub authorization_token: Option<Option<String>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "purpose_hint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub purpose_hint: Option<Option<String>>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl WorkspaceMcpServerUpdate {
    /// Partial update. Only the fields the caller sets are applied.  ``authorization_token`` has three states rather than two, which is what a write-only field needs: omit it to leave the stored token alone, send ``\"\"`` to clear it, send a value to rotate it. An explicit ``null`` also leaves it alone, matching the platform: a client that serializes its whole form back, with an empty token box it never filled in, must not destroy a token it was never shown.
    pub fn new() -> WorkspaceMcpServerUpdate {
        WorkspaceMcpServerUpdate {
            allowed_tools: None,
            authorization_token: None,
            enabled: None,
            name: None,
            purpose_hint: None,
            url: None,
        }
    }
}
