/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceCodeExecutionPolicyUpdate : The policy to store for a workspace, as a whole.  ``PUT`` semantics, ported from the hosted ``CodeExecutionConfigUpsert``: what is sent is what the workspace has afterwards, so an omitted limit is cleared rather than left as it was.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceCodeExecutionPolicyUpdate {
    /// Hint used when a request declares otari_code_execution without one of its own
    #[serde(
        rename = "default_purpose_hint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_purpose_hint: Option<Option<String>>,
    /// False refuses code execution for this workspace
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Ceiling on one execution's runtime in seconds; only ever lowers the effective limit, so at most 60
    #[serde(
        rename = "exec_timeout_s",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub exec_timeout_s: Option<Option<i32>>,
    /// Sandbox image this workspace's code runs in. Must be one the operator curated into sandbox_allowed_session_images (or the deployment's own sandbox_session_image); null uses the deployment's
    #[serde(
        rename = "image",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub image: Option<Option<String>>,
    /// Ceiling on tool-loop iterations; only ever lowers the effective limit, so at most 25
    #[serde(
        rename = "max_iterations",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_iterations: Option<Option<i32>>,
    /// Code-execution tool kinds this workspace may use, from code_execution, bash_code_execution, text_editor_code_execution. Only ever removes one the backend serves; null exposes whatever it serves
    #[serde(
        rename = "tools",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tools: Option<Option<Vec<String>>>,
}

impl WorkspaceCodeExecutionPolicyUpdate {
    /// The policy to store for a workspace, as a whole.  ``PUT`` semantics, ported from the hosted ``CodeExecutionConfigUpsert``: what is sent is what the workspace has afterwards, so an omitted limit is cleared rather than left as it was.
    pub fn new(enabled: bool) -> WorkspaceCodeExecutionPolicyUpdate {
        WorkspaceCodeExecutionPolicyUpdate {
            default_purpose_hint: None,
            enabled,
            exec_timeout_s: None,
            image: None,
            max_iterations: None,
            tools: None,
        }
    }
}
