/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceWebSearchConfigUpdate : The configuration to store for a workspace, as a whole.  ``PUT`` semantics, ported from the hosted ``WorkspaceWebSearchConfigUpdate``: what is sent is what the workspace has afterwards, so an omitted field is cleared rather than left as it was.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceWebSearchConfigUpdate {
    /// Filters Search results and constrains initial and redirected Fetch destinations; intersected with any list the request sends
    #[serde(
        rename = "allowed_domains",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub allowed_domains: Option<Option<Vec<String>>>,
    /// Filters Search results and blocks initial and redirected Fetch destinations; added to any list the request sends
    #[serde(
        rename = "blocked_domains",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blocked_domains: Option<Option<Vec<String>>>,
    /// False refuses web access for this workspace through otari_web_search, otari_web_fetch, and POST /api/v1/search.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Search only: ceiling on results one search returns; only ever lowers the effective limit, so at most 20
    #[serde(
        rename = "max_results",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_results: Option<Option<i32>>,
    /// Provider-native request fields used as defaults (e.g. exa's 'type', searxng's 'engines').
    #[serde(
        rename = "provider_options",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub provider_options: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Search only: hint used when a request declares otari_web_search without one of its own
    #[serde(
        rename = "purpose_hint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub purpose_hint: Option<Option<String>>,
}

impl WorkspaceWebSearchConfigUpdate {
    /// The configuration to store for a workspace, as a whole.  ``PUT`` semantics, ported from the hosted ``WorkspaceWebSearchConfigUpdate``: what is sent is what the workspace has afterwards, so an omitted field is cleared rather than left as it was.
    pub fn new(enabled: bool) -> WorkspaceWebSearchConfigUpdate {
        WorkspaceWebSearchConfigUpdate {
            allowed_domains: None,
            blocked_domains: None,
            enabled,
            max_results: None,
            provider_options: None,
            purpose_hint: None,
        }
    }
}
