/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceMemberBudgetPolicyPublic : One default and its template values.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceMemberBudgetPolicyPublic {
    #[serde(
        rename = "budget_duration_sec",
        deserialize_with = "Option::deserialize"
    )]
    pub budget_duration_sec: Option<i32>,
    #[serde(rename = "budget_id")]
    pub budget_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "max_budget", deserialize_with = "Option::deserialize")]
    pub max_budget: Option<f64>,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "provider_key_id", deserialize_with = "Option::deserialize")]
    pub provider_key_id: Option<String>,
    #[serde(rename = "request_limit", deserialize_with = "Option::deserialize")]
    pub request_limit: Option<i32>,
    #[serde(rename = "reset_alignment", deserialize_with = "Option::deserialize")]
    pub reset_alignment: Option<String>,
    #[serde(rename = "token_limit", deserialize_with = "Option::deserialize")]
    pub token_limit: Option<i32>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "workspace_id")]
    pub workspace_id: uuid::Uuid,
}

impl WorkspaceMemberBudgetPolicyPublic {
    /// One default and its template values.
    pub fn new(
        budget_duration_sec: Option<i32>,
        budget_id: String,
        created_at: String,
        id: String,
        max_budget: Option<f64>,
        name: Option<String>,
        provider_key_id: Option<String>,
        request_limit: Option<i32>,
        reset_alignment: Option<String>,
        token_limit: Option<i32>,
        updated_at: String,
        workspace_id: uuid::Uuid,
    ) -> WorkspaceMemberBudgetPolicyPublic {
        WorkspaceMemberBudgetPolicyPublic {
            budget_duration_sec,
            budget_id,
            created_at,
            id,
            max_budget,
            name,
            provider_key_id,
            request_limit,
            reset_alignment,
            token_limit,
            updated_at,
            workspace_id,
        }
    }
}
