/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkspaceMemberBudgetPolicyUpdate : Request body for pointing a default at a different budget.  Members already materialized from this default keep the budget they were given: their ceiling names it directly, and this only changes what a member joining afterwards is handed. Editing the *budget* is the retroactive act, and it moves everyone naming it, in this workspace and outside it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceMemberBudgetPolicyUpdate {
    #[serde(rename = "budget_id")]
    pub budget_id: String,
}

impl WorkspaceMemberBudgetPolicyUpdate {
    /// Request body for pointing a default at a different budget.  Members already materialized from this default keep the budget they were given: their ceiling names it directly, and this only changes what a member joining afterwards is handed. Editing the *budget* is the retroactive act, and it moves everyone naming it, in this workspace and outside it.
    pub fn new(budget_id: String) -> WorkspaceMemberBudgetPolicyUpdate {
        WorkspaceMemberBudgetPolicyUpdate { budget_id }
    }
}
