/*
 * otari
 *
 * Otari, an OpenAI-compatible LLM gateway with API key management
 *
 * The version of the OpenAPI document: 0.12.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorstAllocationResponse : The row furthest through its allowance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorstAllocationResponse {
    #[serde(rename = "allocated")]
    pub allocated: f64,
    #[serde(rename = "budget_id")]
    pub budget_id: String,
    /// The row's own name, or null where nobody gave it one.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    /// The scope's id, so an unnamed ceiling can be named after it.
    #[serde(rename = "scope_id", deserialize_with = "Option::deserialize")]
    pub scope_id: Option<String>,
    /// What a spend ceiling caps (workspace, org_member, api_token, ...); null for a budget.
    #[serde(rename = "scope_type", deserialize_with = "Option::deserialize")]
    pub scope_type: Option<String>,
    #[serde(rename = "spent")]
    pub spent: f64,
}

impl WorstAllocationResponse {
    /// The row furthest through its allowance.
    pub fn new(
        allocated: f64,
        budget_id: String,
        name: Option<String>,
        scope_id: Option<String>,
        scope_type: Option<String>,
        spent: f64,
    ) -> WorstAllocationResponse {
        WorstAllocationResponse {
            allocated,
            budget_id,
            name,
            scope_id,
            scope_type,
            spent,
        }
    }
}
