/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudioSpeechRequest : OpenAI-compatible audio speech (TTS) request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioSpeechRequest {
    #[serde(rename = "input")]
    pub input: String,
    #[serde(rename = "instructions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<Option<String>>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "response_format", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub response_format: Option<Option<String>>,
    #[serde(rename = "speed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub speed: Option<Option<f64>>,
    #[serde(rename = "user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user: Option<Option<String>>,
    #[serde(rename = "voice")]
    pub voice: String,
}

impl AudioSpeechRequest {
    /// OpenAI-compatible audio speech (TTS) request.
    pub fn new(input: String, model: String, voice: String) -> AudioSpeechRequest {
        AudioSpeechRequest {
            input,
            instructions: None,
            model,
            response_format: None,
            speed: None,
            user: None,
            voice,
        }
    }
}

