/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CcChatCompletionMessageToolCallsInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "function")]
    pub function: models::CcFunction,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "custom")]
    pub custom: models::CcCustom,
}

impl CcChatCompletionMessageToolCallsInner {
    pub fn new(id: String, function: models::CcFunction, r#type: Type, custom: models::CcCustom) -> CcChatCompletionMessageToolCallsInner {
        CcChatCompletionMessageToolCallsInner {
            id,
            function,
            r#type,
            custom,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "function")]
    Function,
    #[serde(rename = "custom")]
    Custom,
}

impl Default for Type {
    fn default() -> Type {
        Self::Function
    }
}

