/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentAnyOfInner {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "refusal")]
    pub refusal: String,
}

impl ContentAnyOfInner {
    pub fn new(text: String, r#type: Type, refusal: String) -> ContentAnyOfInner {
        ContentAnyOfInner {
            text,
            r#type,
            refusal,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "refusal")]
    Refusal,
}

impl Default for Type {
    fn default() -> Type {
        Self::Text
    }
}

