/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationInner {
}

impl LocationInner {
    pub fn new() -> LocationInner {
        LocationInner {
        }
    }
}

