/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "container", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub container: Option<Option<models::MrContainer>>,
    #[serde(rename = "content")]
    pub content: Vec<models::Content9Inner>,
    #[serde(rename = "model")]
    pub model: Box<models::Model>,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "stop_details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stop_details: Option<Option<models::MrRefusalStopDetails>>,
    #[serde(rename = "stop_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<Option<StopReason>>,
    /// Filter models by provider name
    #[serde(rename = "stop_sequence", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stop_sequence: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "usage")]
    pub usage: models::MrUsage,
}

impl MessageResponse {
    pub fn new(id: String, content: Vec<models::Content9Inner>, model: models::Model, role: Role, r#type: Type, usage: models::MrUsage) -> MessageResponse {
        MessageResponse {
            id,
            container: None,
            content,
            model: Box::new(model),
            role,
            stop_details: None,
            stop_reason: None,
            stop_sequence: None,
            r#type,
            usage,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "assistant")]
    Assistant,
}

impl Default for Role {
    fn default() -> Role {
        Self::Assistant
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StopReason {
    #[serde(rename = "end_turn")]
    EndTurn,
    #[serde(rename = "max_tokens")]
    MaxTokens,
    #[serde(rename = "stop_sequence")]
    StopSequence,
    #[serde(rename = "tool_use")]
    ToolUse,
    #[serde(rename = "pause_turn")]
    PauseTurn,
    #[serde(rename = "refusal")]
    Refusal,
}

impl Default for StopReason {
    fn default() -> StopReason {
        Self::EndTurn
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "message")]
    Message,
}

impl Default for Type {
    fn default() -> Type {
        Self::Message
    }
}

