/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModerationRequest : OpenAI-compatible moderation request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModerationRequest {
    #[serde(rename = "input")]
    pub input: Box<models::Input1>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user: Option<Option<String>>,
}

impl ModerationRequest {
    /// OpenAI-compatible moderation request.
    pub fn new(input: models::Input1, model: String) -> ModerationRequest {
        ModerationRequest {
            input: Box::new(input),
            model,
            user: None,
        }
    }
}

