/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MrCitationsConfig {
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl MrCitationsConfig {
    pub fn new(enabled: bool) -> MrCitationsConfig {
        MrCitationsConfig {
            enabled,
        }
    }
}

