/*
 * otari-gateway
 *
 * A clean FastAPI gateway for otari with API key management
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MsgChatCompletionContentPartImageParam : Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MsgChatCompletionContentPartImageParam {
    #[serde(rename = "image_url")]
    pub image_url: Box<models::MsgImageUrl>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl MsgChatCompletionContentPartImageParam {
    /// Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
    pub fn new(image_url: models::MsgImageUrl, r#type: Type) -> MsgChatCompletionContentPartImageParam {
        MsgChatCompletionContentPartImageParam {
            image_url: Box::new(image_url),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "image_url")]
    ImageUrl,
}

impl Default for Type {
    fn default() -> Type {
        Self::ImageUrl
    }
}

